### PR TITLE
Fixes #929: Move the resources directory to src/main

### LINKED ISSUE #929: New 'mockito-inline' artifact does not work
mockito-inline 2.7.2

build.gradle:
```groovy
apply plugin: 'java'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

repositories {
    jcenter()
}

dependencies {
    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-inline:2.7.2'
}
```

Test target:
```java
final class Foo {

}
```

Test for Foo:
```java
public class FooTest {

    @Test
    public void test() {
        Mockito.mock(Foo.class);
    }

}
```

Test command:
```
$ ./gradlew clean test
:clean
:compileJava
:processResources UP-TO-DATE
:classes
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test

com.example.FooTest > test FAILED
    org.mockito.exceptions.base.MockitoException at FooTest.java:10

1 test completed, 1 failed
:test FAILED

FAILURE: Build failed with an exception.
```

Test report:
```
org.mockito.exceptions.base.MockitoException: 
Cannot mock/spy class com.example.Foo
Mockito cannot mock/spy because :
 - final class
	at com.example.FooTest.test(FooTest.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Reason

`mockito-extensions/org.mockito.plugins.MockMaker` is not included in the mockito-inline.jar.
```
$ jar tvf mockito-inline-2.7.2.jar 
     0 Sat Feb 04 12:02:54 JST 2017 META-INF/
    25 Sat Feb 04 12:02:54 JST 2017 META-INF/MANIFEST.MF
```

In [the inline subproject](https://github.com/mockito/mockito/tree/release/2.x/subprojects/inline), org.mockito.plugins.MockMaker is in `src/resources/mockito-extensions` directory.
Is this correct?

In [the android subproject](https://github.com/mockito/mockito/tree/release/2.x/subprojects/android), the file is in src/**main**/resources/mockito-extensions.

### PR DESCRIPTION
**Pull request by tmurakami**
Moved the resources directory to src/main so that the MockMaker file is included in mockito-inline.jar.
Also added two tests to verify plugin-type is inline.

This PR fixes #929.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
I think the path should be `src/test/resources` though, as Mockito is only used during testing.

**Comment by tmurakami** [comment]
According to #920, this library seems to enable mock-maker-inline without setting.

I suppose that its usage is as follows:
```groovy
dependencies {
    testCompile 'org.mockito:mockito-inline:+'
}
```
However, as shown in #929, mockito-inline.jar does not include the MockMaker configuration file, so mock-maker-inline cannot be enabled.
To include the configuration file in this jar, I think the path is src/main/resources.

**Comment by bric3** [comment]
@TimvdLippe `src/test` is not packaged ;)

**Comment by TimvdLippe** [comment]
Ah of course. My mistake

**Pull request merged**
