### PR TITLE
use Dependabot 2

### PR DESCRIPTION
**Pull request by sullis**
Reference:

https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

https://help.github.com/en/github/administering-a-repository/about-github-dependabot

check list

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by sullis** [comment]
LGTM

**Comment by edumco** [comment]
> I am not familiar with this dependency, but the upgrade SGTM

Dependabot checks the dependencies and automatically opens a pull request whenever a new version is releases and this new version is owned and integrated by Github

**Comment by sullis** [comment]
ping @mockitoguy

**Comment by sullis** [comment]
ping @mockitoguy

**Review by TimvdLippe — APPROVED** [review]
I am still not sure if we want to start using Dependabot more often, but I guess this PR on its own makes sense. So I am merging this for now.

**Pull request merged**
