### PR TITLE
Fixes Issue #1542: When verify fails show all method invocations

### PR DESCRIPTION
**Pull request by mrhampson**
This PR fixes issue #1542 (when mock is called multiple times, and verify fails, the error message reports only the first invocation). From the issue, the idea is that showing all invocation would make it easier to see why something failed.

I have changed the behavior of the exception thrown and it's message now contains all method invocations instead of only the first one.
New format: 
```
Argument(s) are different! Wanted:
exampleBuilder.with("key1", "wrongValue");
-> at org.mockitousage.verification.VerifyPrintsAllInvocationsOnErrorTest.shouldPrintAllInvocationsOnError(VerifyPrintsAllInvocationsOnErrorTest.java:23)
Actual invocations have different arguments:
exampleBuilder.with("key1", "val1");
-> at org.mockitousage.verification.VerifyPrintsAllInvocationsOnErrorTest.shouldPrintAllInvocationsOnError(VerifyPrintsAllInvocationsOnErrorTest.java:20)
exampleBuilder.with("key2", "val2");
-> at org.mockitousage.verification.VerifyPrintsAllInvocationsOnErrorTest.shouldPrintAllInvocationsOnError(VerifyPrintsAllInvocationsOnErrorTest.java:21)
```

### CODE REVIEW

**Comment by mrhampson** [comment]
I realized that this doesn't list out the locations as well as all the calls. I'll push something to improve that.

**Comment by mockitoguy** [comment]
Thank you. Let us know when you got this completed.

Can you test the behavior in IDEA? ArgumentsAreDifferent exception integrates with IDEA and shows the diff/comparison in a pop-up.

**Comment by mrhampson** [comment]
@mockitoguy This should have all the changes completed now.
I used IntelliJ when I was developing this and I believe the pop up works but I will double check later today.

**Comment by mrhampson** [comment]
@mockitoguy Here's the current behavior on IntelliJ. The diff is shown. However it shows all invocations in one diff and I'm not sure if that's the behavior we want or not. Should we have separated diffs for each invocation?

screen shot 2018-12-03 at 11 48 41 am
screen shot 2018-12-03 at 11 48 55 am

**Comment by mrhampson** [comment]
@bric3 Updated the PR. Let me know if you need more detail on anything.
I'm not sure what I should do to clean up the commit messages themselves. I guess I could always squash them into one commit.

**Comment by mrhampson** [comment]
@bric3 Tried to just rebase and clean up the commit history.

**Comment by mrhampson** [comment]
@mockitoguy @bric3 Can this still be merged or should I just close this?

**Comment by TimvdLippe** [comment]
I will manually merge this in a new PR. Thanks for the initial contribution!

**Pull request closed without merging**
