### PR TITLE
Revert "Update objenesis to 3.1"

### LINKED ISSUE #2007: Android instrumentation test packaging fails for mockito-android 3.5.0 with minSdk < 26
We've upgraded from `mockito-android:3.4.6` to `mockito-android:3.5.0`. I'm attempting to package up my instrumented tests by running the `assembleAndroidTest` gradle task. The task fails with the following errors:
```
/Users/<me>/.gradle/caches/transforms-2/files-2.1/fb7959dc5bfc8ebb26ad0660efa1929e/jetified-mockito-core-3.5.0.jar: D8: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
/Users/<me>/.gradle/caches/transforms-2/files-2.1/4d4498fa5552ba637b5a9594a0871b80/jetified-objenesis-3.1.jar: D8: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
/Users/<me>/.gradle/caches/transforms-2/files-2.1/4d4498fa5552ba637b5a9594a0871b80/jetified-objenesis-3.1.jar: D8: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
```

and with root cause:
```
com.android.tools.r8.utils.b: Error: /Users/<me>/.gradle/caches/transforms-2/files-2.1/4d4498fa5552ba637b5a9594a0871b80/jetified-objenesis-3.1.jar:org/objenesis/instantiator/util/DefineClassHelper$Java8.class, java.lang.Class org.objenesis.instantiator.util.DefineClassHelper$Java8.defineClass(java.lang.String, byte[], int, int, java.lang.Class, java.lang.ClassLoader, java.security.ProtectionDomain), MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
        at com.android.tools.r8.utils.y0.a(:21)
        at com.android.tools.r8.utils.O.a(:51)
        ... 35 more
```

### PR DESCRIPTION
**Pull request by TimvdLippe**
Reverts mockito/mockito#1998

See #2007 for more info on how this breaks Android

Fixes #2007

### CODE REVIEW

**Comment by raphw** [comment]
Annoying but probably the best option. Maybe we can explicitly downgrade Objenesis in the *mockito-android* artifact instead?

**Review by raphw — COMMENTED** [review]
Wondering if we can just downgrade the version in *mockito-android*? What errors did the new Objenesis fix? Maybe it's required to work with the newest Java versions?

**Review by raphw — COMMENTED** [review]
Wondering if we can just downgrade the version in *mockito-android*? What errors did the new Objenesis fix? Maybe it's required to work with the newest Java versions?

**Comment by TimvdLippe** [comment]
Hm yes that could work. I can test that out tomorrow.

**Comment by kozaxinan** [comment]
This issue still blocks android projects to use latest mockito. Is further work planned on this PR? If not I can provide a different PR with requested fix.

**Comment by TimvdLippe** [comment]
I have not yet had the time to do an analysis on this issue. If you have a proposed fix and you can confirm it works, I would be very happy to review it! Thanks in advance 😄

**Comment by raphw** [comment]
Just to be sure: did you try to downgrade Objenesis explicitly? Are you using *mockito-android*?

**Comment by kozaxinan** [comment]
We downgraded objenesis version with gradle dependency resolutions. 
```
configurations.configureEach {
    resolutionStrategy.eachDependency { details ->
     if (details.requested.group == 'org.objenesis') {
        details.useVersion '2.6'
      } 
    }
  }
```
This worked well. We have `mockito-android` too, but in most case we also have `mockito-core` with `com.nhaarman.mockitokotlin2:mockito-kotlin`

I will build a mockito-android with older objenesis and check the fix. (It might take time)

**Comment by raphw** [comment]
Thank you.

My favorit solution would be to fix the version for Android-specific artifacts but use the latest for core to support newer Java versions.

**Comment by kozaxinan** [comment]
I have experimented downgrading objenesis just in mockito-android. When mockito-android is used with mockito-kotln, gradle uses higher version from mockito-kotlin. If you know any gradle/maven trick to strictly force transitive dependency we could apply in https://github.com/mockito/mockito/pull/2024.

**Comment by TimvdLippe** [comment]
This was fixed in #2024

**Pull request closed without merging**
