### PR TITLE
Automatic dependency update with Dependabot

### PR DESCRIPTION
**Pull request by szpak**
Configuration for [Dependabot](http://dependabot.com/) to evaluate automatic dependency update (via PRs).

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Travis was unhappy, but that should be fixed on `release/2.x` and would need a simple rebase.

It seems like the parser is specified in https://github.com/dependabot/dependabot-core/blob/master/gradle/lib/dependabot/gradle/file_parser/property_value_finder.rb and that would need to be updated to support our pattern (or we change our pattern to something that is compatible with dependabot).

**Comment by szpak** [comment]
Thanks @TimvdLippe for looking on it. I created an [issue](https://github.com/dependabot/feedback/issues/345). It would be good to work out some easy to match with regex good practices to re-use also in other Gradle projects.
I propose to merge it as is (after Travis is happy), activate via GitHub Market to see the current results and see changes after potential improvement on their side (Dependabot seems to use Continuous Delivery).

**Comment by szpak** [comment]
@TimvdLippe https://github.com/dependabot/feedback/issues/345 is fixed. Can you accept that PR?

**Comment by szpak** [comment]
I had problem reaching out @mockitoguy to enable [Dependabot](https://github.com/marketplace/dependabot/), so in the end I tested it with my fork. Seem quite ok: https://github.com/szpak/mockito/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies.

**Pull request merged**
