### PR TITLE
Introduce test for mock-maker-inline with Kotlin suspend functions

### PR DESCRIPTION
**Pull request by elizarov**
See issue #1152
This test should pass when byte-buddy is updated with https://github.com/raphw/byte-buddy/pull/332

### CODE REVIEW

**Comment by elizarov** [comment]
I've update this PR with Kotlin 1.1.4-3 that fixes problem in #1152 and makes the test pass

**Comment by raphw** [comment]
Awesome, thanks, we will merge this shortly. Improving Byte Buddy to handle this scenario better is on my list of things to do but this makes the issue less pressing. I think its good for Kotlon with regards to compatibility with tooling anyways!

**Comment by TimvdLippe** [comment]
Travis seems unhappy on jdk7. Not sure what is going on, but need to verify it is working on 7 before merging.

**Comment by raphw** [comment]
It is because the Kotlin plugin being used seems to require Java 8.

That is too bad, we probably need to add a rule to only build the test on Java 8+ VMs.

**Comment by elizarov** [comment]
Yes. Kotlin compiler infrastructure had been recently moved to JDK8. The produced bytecode still targets JDK6 by default, but the compiler and all the tools around it require JDK8.

**Comment by TimvdLippe** [comment]
> That is too bad, we probably need to add a rule to only build the test on Java 8+ VMs.

A shame, but better than nothing. @elizarov if you have the time, would you be able to include that in this PR to make Travis happy again? :smile:

**Comment by szczepiq** [comment]
Kotlin 1.1.2 requires JDK 8 ([JetBrains blog post](https://blog.jetbrains.com/kotlin/2017/04/kotlin-1-1-2-is-out/)). Let's skip building/running Kotlin integration test in Java7 builds. Perhaps it is enough to conditionally include "kotlinTest" subproject in settings.gradle, based on the version of Java?

@szpak, you did good cool stuff with our Gradle automation, do you want to take a stab at it?

**Comment by TimvdLippe** [comment]
We are no longer building on jdk7 per https://github.com/mockito/mockito/commit/da3f20eeb4db9fc78249d1b95a2548e68e9908a4 @elizarov could you rebase to retrigger Travis, then we can merge 🎉

**Comment by elizarov** [comment]
Rebased

**Pull request merged**
