### PR TITLE
Fixes Google Code issue 409 - added invocation of describeMismatch where possible so it's...

### LINKED ISSUE #409: Selective capturing matcher
Creating an issue tracker for a feature request.

A small team i've been working with has created an extended use case wrapping Mockito. We'd like to add in some of the functionality that we've found to be particular useful during our own development.

One such item is an ArgumentCaptor that matches on a provided ArgumentMatcher. We've had several use cases within our own library where we'd like capture an argument that meets a certain condition, and leverage that captured argument for additional verification or reporting.

You _could_ capture the value, then match it against the provided matcher in a separate step. This alleviates the extra work.

Usage example:
We have an API that emits a host of Kafka (http://kafka.apache.org/) events. It's hyper-critical that we have high test coverage for the various events that we emit, so we created a separate TestNG reporter (http://testng.org/javadocs/org/testng/IReporter.html) to generate a basic coverage report (events tested / total events). As the user makes verification on the events they've emitted (using custom matchers), we capture and log them to the reporter.

### PR DESCRIPTION
**Pull request by mzoltan**
Reflectively invoking describeMismatch when possible.
[Google code issue 409](https://code.google.com/p/mockito/issues/detail?id=409)

### CODE REVIEW

**Comment by bric3** [comment]
Could you replace in the commit message the `#` by `issue`, github inspect each commits and will link to the PR 409 (even if not yet existing), GH may even mark the PR / issue merged.

**Comment by mzoltan** [comment]
You mean "Fixes issue409 - ..."? CONTRIBUTING.md should be updated with
this info I think.

Nope I did not, I only tested with the shipped version. Is it enough if I
test with the latest or did you have other specific versions in mind?

2015-02-08 18:38 GMT+01:00 Brice Dutheil <notifications@github.com>:

**Comment by bric3** [comment]
> You mean "Fixes issue409 - ..."? CONTRIBUTING.md should be updated with this info I think.

Good point, thx :smile: 

> Nope I did not, I only tested with the shipped version. Is it enough if I test with the latest or did you have other specific versions in mind?

Actually I it would good to see if this change is compatible across hamcrest versions 1.1, 1.2, 1.3 as long as mockito depends on Hamcrest internally see #154

**Comment by mzoltan** [comment]
So I created a test application with only the mockito jar, objenesis 1.2
and hamcrest versions 1.1, then 1.2 and 1.3. All work as expected, starting
from version 1.2 the describeMismatch method is of course mandatory and is
being picked up all the same by mockito.

2015-02-08 19:00 GMT+01:00 Brice Dutheil <notifications@github.com>:

**Comment by bric3** [comment]
cool, I'll test your code asap.

One task that may prove useful to automatize this test is to make "integration" sub-projects

**Comment by mzoltan** [comment]
Hey Brice,

I was wondering if there's an estimate as to when/if this change will be
released? As it happens I could really use this in my work but I'm only
supposed to work with disted versions :)

Thanks

2015-02-15 22:42 GMT+01:00 Brice Dutheil <notifications@github.com>:

**Comment by mzoltan** [comment]
Hey Brice,

Will this be merged do you think? It's been a while but I'm happy to rebase if it's considered for 2.0.

**Comment by szczepiq** [comment]
Hey, we cannot merge this as I have changed hamcrest integration rather drastically recently. Mockito no longer uses hamcrest internally.

If you still believe that this feature is useful, can you show us how? E.g. can you show as textual view of a verification failure that demonstrates the usefulness of describing mismatches?

**Comment by mzoltan** [comment]
Sure, I had this Network#send(EncodedMessage msg) method and I mocked Network and used a ContainsEntity matcher to make assertions on the contents of the encoded message. The matcher would decode the msg and check whether the contents contained what I expected. You can see how it was not very useful when the match failed, I got something like:

Expected: "a message containing: MyEntity"
Got: 129dh3jaksjSI&Dh2k8ad... etc. (the toString of EncodedMessage)

It would have been useful to know what was in that message, rather than its toString.

**Pull request closed without merging**
