### PR TITLE
Fixes #2311 : print the fully qualified class names.

### LINKED ISSUE #2311: Print the fully qualified class names if the simple class names are the same
I have 2 overloads of a method:
* `setDeadline(java.time.Duration)`
* `setDeadline(org.joda.time.Duration)`

There's a mocking failure in a test (calling the wrong overload), but the error message isn't super helpful:

```
1) myMethod(com.google.frobber.MyClassTest)
Argument(s) are different! Wanted:
myClass.setDeadline(
    (Duration) PT1S
);
-> at com.google.frobber.MyClassTest.myMethod(MyClassTest.java:287)
Actual invocation has different arguments:
myClass.setDeadline(
    (Duration) PT1S
);
```

The output attempts to include the classnames to help disambiguate, but in this case, the simple class names are identical (`Duration`). We should be able to detect this, and print the FQCNs if the simple names are equal.

Alternatively, we could always print the FQCNs:

https://github.com/mockito/mockito/blob/6f9108b833323345bd926f10914224d3e0a11b80/src/main/java/org/mockito/internal/matchers/Equals.java#L55

(We already do something similar in Truth.)

### PR DESCRIPTION
**Pull request by chaehwanli**
## Checklist

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

-. replace getName() with getSimpleName()

### CODE REVIEW

**Comment by TimvdLippe** [comment]
We no longer use the `release/3.x` branch, so #2320 suffices for now. I think I will have a chance tomorrow to review the PR.

**Comment by chaehwanli** [comment]
I'm just showing that I'm a complete beginner.
Using the release branch for PR... I'm sorry for wasting your time.

**Comment by TimvdLippe** [comment]
Don't worry about it, our branch naming was confusing! It's an easy mistake to make, so no worries at all 😄

**Comment by chaehwanli** [comment]
thank you~ :)

**Pull request closed without merging**
