### PR TITLE
Add gradle benchmark task to test performance of Mockito

### PR DESCRIPTION
**Pull request by TimvdLippe**
You can run this benchmark with `./gradlew jmh`. This adds a very simple benchmark suite which we can extend later too if we want to.

Related to #851

### CODE REVIEW

**Comment by TimvdLippe** [comment]
@raphw I have updated the benchmarks. The first benchmark is correct I think (with the custom classloader), however the second one isn't. The reason being that I can't seem to cast to the correct class after invoking `loader.loadClass()`. It seems that the cast has a different `Class` than what the loader returns, even though they are both `IMethods.class`

**Comment by raphw** [comment]
A class is only if its the same type name and loaded by the same class loader. You have to use reflection for such interaction or define a common super interface; maybe create a subclass of `IMethods` (using ByteBuddy), load this class in a different class loader (`ClassLoadingStrategy.Default.WRAPPER`) and create a mock of this class.

**Comment by TimvdLippe** [comment]
@raphw I tried to turn your comment into code, but sadly it is still happening. It complains that the type of the class returned by `Mockito.mock` is not a subclass of `IMethods`.

**Comment by TimvdLippe** [comment]
I am unable to progress on this PR as I clearly lack the experience and knowledge. Could someone maybe help out? :heart:

**Comment by TimvdLippe** [comment]
Can't seem to get this to work. Closing the PR for now, but we can leave the branch alive.

**Pull request closed without merging**
