### PR TITLE
Remove unused VoidMethodStubbable

### PR DESCRIPTION
**Pull request by TimvdLippe**
Since `Mockito#stubVoid` has been removed, we can remove this class too.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Tests are now actually fixed, had to run `./gradlew clean` to make sure the compiled classes were removed. @raphw PTAL

**Comment by PascalSchumacher** [comment]
I guess this is superseded by https://github.com/mockito/mockito/commit/da34c534d6ac6b6fb63ffce68ed81b42bca0ebbb ?

**Comment by TimvdLippe** [comment]
Um yes it appears that @raphw manually merged this into master.

**Comment by raphw** [comment]
Sorry, bad synchronization from my end, I saw there were some left bits when I fixed some documentation links that pointed to dead classes.

**Pull request closed without merging**
