### PR TITLE
Artifacts are now published to 'mockito' org in Bintray

### LINKED ISSUE #669: Publish mockito artifacts to 'mockito' organization in Bintray
Instead of publishing to 'szczepiq' user, the artifacts should be published to 'mockito' organization in Bintray.

### PR DESCRIPTION
**Pull request by szczepiq**
Fixes #669, more details in the commit message.

### CODE REVIEW

**Comment by bric3** [comment]
Maybe update badge links (and in a second time) on readme page as well

**Comment by bric3** [comment]
Anyway hurray 🍾

**Comment by bric3** [comment]
In facts links to bintray.com/szczepiq are already broken

**Comment by TimvdLippe** [comment]
> In facts links to bintray.com/szczepiq are already broken

Our previous release candidates were pointing to these links and are therefore broken

**Comment by szczepiq** [comment]
Let's point them to maven central. Sorry about the breakage. I could have predicted that changing ownership of the repo moves links. Do we need a remedy plan? I can transfer the ownership back to me.

**Comment by TimvdLippe** [comment]
No do not revert the ownership. It is okay for now

**Comment by bric3** [comment]
You mean redirect to the _legacy system_ ? 😈

**Comment by szczepiq** [comment]
>You mean redirect to the legacy system ? 😈

Central repo is fine :), it's just maven as the build tool is legacy 🗡 

Merging!

**Pull request merged**
