### PR TITLE
#2522: mockito-inline & Groovy NullPointerException 

### PR DESCRIPTION
**Pull request by stevegreenn**
Hi!

It was requested by @TimvdLippe that I create a pull request with a new subproject that tests Groovy and mockito-inline. See here: https://github.com/mockito/mockito/issues/2522#issuecomment-1011376058

Unfortunately this test is currently failing as part of the `./gradlew clean build`, still throwing a NullPointerException. Hopefully the new subproject can be used to track the issue down though.

Steve

### CODE REVIEW

**Comment by raphw** [comment]
Thanks, I'll see what we can do about this!

**Comment by raphw** [comment]
I do not get an error when running this test, it passes.

You can extract the class files using `-Dnet.bytebuddy.dump=/some/folder`. Could you compare the instrumented files and suggest what methods should not be instrumented?

**Comment by TimvdLippe** [comment]
Per https://github.com/mockito/mockito/issues/2522#issuecomment-1069615814 I think we need to update this PR to include https://github.com/mockito/mockito/commit/81bc5bd2ef05ffc16b3a76823fa5e4d15ee66dba, would we not? That said, we do need the regression test to fail without any modifications and then it would need to pass with the fix. Otherwise, it is not catching the correct error.

Lastly, @stevegreenn can you run `./gradlew spotlessApply` on your PR so that it gets formatted correctly?

**Comment by raphw** [comment]
@stevegreenn Could you rebase your PR on my change and see if the test is still failing?

**Comment by TimvdLippe** [comment]
@nick-ernie confirmed in https://github.com/mockito/mockito/issues/2522#issuecomment-1070921396 that https://github.com/mockito/mockito/commit/61279b27869f081551c5ae287216967013ee5e3b should fix the issue.

@stevegreenn can you incorporate the above commit or would you prefer us to take in your PR and get it ready-for-merge?

**Comment by stevegreenn** [comment]
Thanks for the further work on this guys! I'll get this PR updated later today.

**Review by TimvdLippe — APPROVED** [review]
Nice fix, thanks for bearing with us!

**Comment by TimvdLippe** [comment]
@stevegreenn Seems like there was a compilation failure on the commit. Can you check it out and verify that `./gradlew build` runs locally?

**Comment by stevegreenn** [comment]
Looks like there is indeed a compilation error. From a quick glance, it looks like this is the problem:

https://github.com/mockito/mockito/pull/2566/files#diff-749d9baac17dc6e18e7db9ee686a840d65ac746dc291b591b37834ba4c8261d1R394

The method definition (found [here](https://github.com/mockito/mockito/pull/2566/files#diff-ae35471e0471321b026f5b500c35bb52d82365b1a6a19e1e00e06de930d31416R23)) requires a boolean parameter, which isn't being provided in the above snippet.

@raphw - can you take a look please? I'm on holiday at the minute but if it's as simple as adding true/false there I can make that change, or I can bring in another commit again.

**Comment by TimvdLippe** [comment]
It's probably easier if we (as maintainers) push to your branch to fix it up to get it submitted. That way, we can ensure credit on the commits and get this merged.

**Comment by raphw** [comment]
Was this due to a merge conflict? My branch is building fine.

**Comment by HonorKnight** [comment]
@TimvdLippe @stevegreenn is anyone working on this? it seems to have stagnated a bit, and this fix would be invaluable to me if it can move forward.

**Comment by raphw** [comment]
I cherry-picked the test project onto my branch here: https://github.com/mockito/mockito/pull/2618

Once @TimvdLippe reviews the PR, I can merge it and create a new release.

**Comment by TimvdLippe** [comment]
This landed in #2618

**Pull request closed without merging**
