### PR TITLE
Fixed problem with publication

### PR DESCRIPTION
**Pull request by szczepiq**
- stopped publishing android module to main repo for now
- added project description, required by bintray

### CODE REVIEW

**Comment by ChristianSchwarz** [comment]
Hmm my build failed, may be it relates to this PR?

https://travis-ci.org/mockito/mockito/builds/184827896

Log-Entry:
```
:assertEnvVariables FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/home/travis/build/mockito/mockito/gradle/root/release.gradle' line: 170

* What went wrong:
Execution failed for task ':assertEnvVariables'.
> Please export 'GH_TOKEN' env variable first. Expression: java.lang.System.env[it]. Values: it = GH_TOKEN



```

**Comment by szczepiq** [comment]
@ChristianSchwarz, this is one of the env variables the release task requires. For normal builds, this env var is not needed. You need to export it to do local release testing. It's not ideal, it's how it is now :)

**Comment by ChristianSchwarz** [comment]
@szczepiq Thanks for your answer! The local build is no problem, the travis build failed (see link aboive) of PR #833.

**Comment by szczepiq** [comment]
Thank you for your patience. I will work on making the release procedure easier to test for everybody.

**Comment by bric3** [comment]
@szczepiq THX

**Pull request merged**
