### PR TITLE
replace TestBase#assertContainsType(final Collection<?> list, final C…

### PR DESCRIPTION
**Pull request by PascalSchumacher**
…lass<?> clazz) with AssertJ assertion

### CODE REVIEW

**Comment by TimvdLippe** [comment]
LGTM

**Comment by TimvdLippe** [comment]
Ah but it requires a rebase :(

**Comment by PascalSchumacher** [comment]
rebased

**Comment by bric3** [comment]
Thanks @PascalSchumacher ! 

...Once we can work on mockito 3 we will have java 8 and we can update AssertJ to version 3.x as well and have a richer assertion API in our tests.

**Comment by PascalSchumacher** [comment]
>Thanks @PascalSchumacher ! 

You are welcome. 

Thanks for letting me contribute to a great project like mockito. :)

**Pull request merged**
