### PR TITLE
Prepare Android library for publication and bump version to 2.6.0

### PR DESCRIPTION
**Pull request by TimvdLippe**
References first step of #848

### CODE REVIEW

**Comment by raphw** [comment]
Actually, I might have found a way to improve this. Will check Monday!

**Comment by TimvdLippe** [comment]
@raphw given that your PR has been merged, we can get this going again right?

**Comment by raphw** [comment]
Yes, please, all good to go!

**Comment by TimvdLippe** [comment]
Conflict has been resolved :tada:

**Comment by bric3** [comment]
Nice !

**Pull request merged**
