### PR TITLE
Clean up issues reported by IntelliJ

### PR DESCRIPTION
**Pull request by TimvdLippe**
Some general issues reported by IntelliJ. Mostly concerning modifiers and unused imports.

### CODE REVIEW

**Comment by raphw** [comment]
Did you upgrade to Java 7? We are still compiling to Java 5 even though Byte Buddy requires Java 6 anyways.

**Comment by TimvdLippe** [comment]
No I did not upgrade to Java 7, why?

**Comment by raphw** [comment]
Try with ressources and diamond operators are Java 7 features.

**Comment by TimvdLippe** [comment]
Oh I thought they were Java 5 features. Why is Travis not failing on that? :O

Will revert these changes then :(

**Comment by raphw** [comment]
I assume Travis runs Java 8 but compiles back to Java 5.

**Comment by PascalSchumacher** [comment]
The travis build uses Java 7: https://github.com/mockito/mockito/blob/master/.travis.yml#L18

**Comment by raphw** [comment]
Sorry, this is painful to ask for, but could you rebase this?

**Comment by TimvdLippe** [comment]
Will rebase this weekend when I have time.

**Comment by bric3** [comment]
Once mockito 2 is released I think we can focus on a pure Java 8 release

**Comment by TimvdLippe** [comment]
@raphw Rebased :smile:

**Pull request merged**
