### PR TITLE
ArgumentCaptor no longer working for varargs

### LINKED ISSUE #188: ArgumentCaptor no longer working for varargs
I ran into the issue described here: http://stackoverflow.com/questions/27303562/why-does-upgrading-mockito-from-1-9-5-to-1-10-8-break-this-captor

### PR DESCRIPTION
**Pull request by lukasz-szewc**
Fixes #188 . These commits should fix issue with capturing varargs.

### CODE REVIEW

**Comment by bric3** [comment]
Hi, thanks for the PR

I will take a look at it soon. And probably merge it. In the mean time, git history is fine except the merge commit, can you get rid of it ?

Otherwise I'll have to cherry-pick relevant commits.

**Comment by lukasz-szewc** [comment]
I will try to do rebase and then do 'force' push. Hope it will work. 
Take a look...

**Comment by bric3** [comment]
Commit looks good, but indeed there's some conflict to narrow down. I'll take a look later, thanks for the rebase ;)

**Comment by lukasz-szewc** [comment]
now it should work...

**Comment by bric3** [comment]
Thanks ;)

**Pull request merged**
