### PR TITLE
update gradle to v3.5

### PR DESCRIPTION
**Pull request by epeee**
While working on #1098 I realized that mockito is still using gradle 2.x. Since java 7 is used now for building and a local build using gradle 3.5 was successful I think we should give 3.5 a try.

### CODE REVIEW

**Comment by szpak** [comment]
Btw, I cleared up the Travis cache for 2.x (which had ~1,2GB) to prune stuff related to old Gradle versions.

**Comment by szpak** [comment]
Re-triggered builds with 3.5 took similarly long to the times before an upgrade.

**Comment by szczepiq** [comment]
>Btw, I cleared up the Travis cache for 2.x (which had ~1,2GB) to prune stuff related to old Gradle versions.

That's great! How did you do it?

**Comment by szczepiq** [comment]
>The execution time increased by around 30 seconds per build

Thank you for investigating it! You're right, we cannot stay on Gradle 2. Gradle 4 will be released in few weeks from now and we cannot keep using version that is over 2 years old.

**Comment by szczepiq** [comment]
@epeee, nice change! I could swear I have even created a ticket in our tracker to get us to Gradle 3.5 :)

**Comment by szpak** [comment]
@szczepiq I've used [Travis UI](UIhttps://docs.travis-ci.com/user/caching#clearing-caches).

Btw, I clear up also caches for other branches just for sanity.

image

**Comment by szczepiq** [comment]
>@szczepiq I've used Travis UI.

Damn, I did not know that Travis has UI to purge caches!

**Pull request merged**
