### PR TITLE
Add new artifact mockito-subclass (to use mock-maker-subclass MockMaker)

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
Related to https://github.com/mockito/mockito/issues/2589#issuecomment-1328262373

## Checklist

 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [ ] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [ ] Avoid other runtime dependencies
 - [ ] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [X] The pull request follows coding style
 - [ ] Mention `Fixes #<issue number>` in the description _if relevant_
 - [ ] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by reta** [comment]
@TimvdLippe could you please take a look if I correctly implemented your idea, thank you

**Comment by TimvdLippe** [comment]
In the CI logs of the Java 8 job with the `mock-maker-subclass`  I see a lot of exceptions coming from `MockUtil`. Can you check whether it is configured correctly and why it is throwing these? I am a bit confused, as the code looks good and I don't see any obvious reason why this would start failing. And why the CI job itself is green anyways.

**Comment by reta** [comment]
> In the CI logs of the Java 8 job with the `mock-maker-subclass` I see a lot of exceptions coming from `MockUtil`. Can you check whether it is configured correctly and why it is throwing these? I am a bit confused, as the code looks good and I don't see any obvious reason why this would start failing. And why the CI job itself is green anyways.

@TimvdLippe just to confirm we are on the same page, I see this assertion:

```
2022-12-13T08:23:29.2135998Z     java.lang.AssertionError
2022-12-13T08:23:29.2136388Z         at org.mockito.internal.util.MockUtil.getMockHandlerOrNull(MockUtil.java:160)
2022-12-13T08:23:29.2136849Z         at org.mockito.internal.util.MockUtil.isMock(MockUtil.java:147)
2022-12-13T08:23:29.2137322Z         at org.mockito.internal.util.DefaultMockingDetails.isMock(DefaultMockingDetails.java:32)

```

If that's the one you have in mind - it is all over the place (all builds I mean), the assertions is gone on retry

**Comment by TimvdLippe** [comment]
Yes that's the one I spotted. I don't think we have these assertions on master, do we? If it is on master we can safely ignore it for this PR, but we should fix it in a separate PR.

**Comment by reta** [comment]
Yeah, I saw it on local builds (master) and CIs, we could probably see that on https://github.com/mockito/mockito/pull/2804 (needs your approval please for workflow run)

**Comment by TimvdLippe** [comment]
Ugh yeah you are correct. Filed #2823 for this. This PR LGTM, thanks!

**Pull request merged**
