### PR TITLE
Make use of Shipkit v2.1.3

### PR DESCRIPTION
**Pull request by mstachniuk**
After this update the site:
https://github.com/mockito/mockito/releases
will be updated by Shipkit

> Hey, 
> 
> Thanks for the contribution, this is awesome.
> As you may have read, project members have somehow an opinionated view on what and how should be
> Mockito, e.g. we don't want mockito to be a feature bloat.
> There may be a thorough review, with feedback -> code change loop.
> 
> Which branch : 
> - On mockito 2.x, make your pull request target `release/2.x`
> - On next mockito version make your pull request target `master`
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/PULL_REQUEST_TEMPLATE.md`

check list

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/2.x/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by TimvdLippe** [comment]
I would like to merge this, but it seems like https://github.com/mockito/shipkit/pull/766 has not been reviewed? Are we certain Shipkit works as intended? (We previously had some release issues, having us to revert the version bump)

**Comment by mstachniuk** [comment]
Yes, it wasn't reviewed. I waited over 2 weeks for review, but nobody did it :-( 
It happens sometimes that the revert is needed. In Shipkit case I or @mockitoguy can quickly fix the issue.

But indeed you had a good feeling. I tested new Shipkit with Shipkit-example project and new functionality doesn't work. 
The fix is on the way: https://github.com/mockito/shipkit/issues/775
and I will update this PR when it's ready.

**Comment by mockitoguy** [comment]
I've tested it by running:

 - ./gradlew testRelease
 - ./gradlew updateReleaseNotes -Ppreview

Everything looks good. I will merge once Travis completed and is green. Thank you @mstachniuk!!!

**Comment by mstachniuk** [comment]
Yes, 2.1.3 works as expected. Example of releases notes uploaded by Shipkit to GitHub: https://github.com/mockito/shipkit-example/releases/tag/v0.16.20
The author of the release notes depends on who generated GitHub write token.
No problem @mockitoguy

**Pull request merged**
