### PR TITLE
Extra test case, javadoc update

### PR DESCRIPTION
**Pull request by mockitoguy**
Let's keep adding test cases to ensure great coverage of the entire behavior.

Also updated documentation so that we consistently use the "lenient" vocabulary.

Stumbled upon it when working on #1272

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Is this intended to be merged before or after #1272?

**Comment by mockitoguy** [comment]
>Is this intended to be merged before or after #1272?

Yes. To keep #1272 smaller, I will be posting unrelated improvements in separate PRs.

**Comment by mockitoguy** [comment]
@TimvdLippe, ok to merge?

**Comment by mockitoguy** [comment]
Thanks! Merging.

**Pull request merged**
