### PR TITLE
[#1202] Java 9 CI build for Mockito 2.x

### LINKED ISSUE #1198: "Could not initialize inline Byte Buddy mock maker" with Gradle 4.x
I tried to add Java 9 build for the Mockito 2.x branch which in turn requires Gradle upgrade to 4.x. Unfortunately with Gradle 4.x (tested with 4.0.1 and 4.2.1) 38 inline mock maker related tests are broken (without `MOCK_MAKER` env variable defined).

For example:
```
org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMakerTest > should_create_mock_from_interface FAILED
    org.mockito.exceptions.base.MockitoInitializationException: 
    Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

    Java               : 1.8
    JVM vendor name    : Oracle Corporation
    JVM vendor version : 25.144-b01
    JVM name           : OpenJDK 64-Bit Server VM
    JVM version        : 1.8.0_144-b01
    JVM info           : mixed mode
    OS name            : Linux
    OS version         : xxx
        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:171)
        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMakerTest.<init>(InlineByteBuddyMockMakerTest.java:35)

        Caused by:
        java.lang.IllegalStateException: 
        The MockMethodDispatcher class file is not locatable: org/mockito/internal/creation/bytebuddy/MockMethodDispatcher.raw

        The class loader responsible for looking up the resource: sun.misc.Launcher$AppClassLoader@73d16e93
```

Travis build reproducing that issue with Oracle JDK (just Gradle upgrade in the `brokenWithGradle4` branch):
https://travis-ci.org/mockito/mockito/jobs/283893407#L793

I don't know why the Gradle upgrade can result in that behavior. Especially that "The MockMethodDispatcher class file is not locatable: org/mockito/internal/creation/bytebuddy/MockMethodDispatcher.raw" sounds strange.

@raphw Under what circumstances that BB error can occur (even abstracting it from Gradle)?

### PR DESCRIPTION
**Pull request by szpak**
## Summary

Provide Java 9 Travis build to ensure Java 9 compatibility in at least tested use cases.

Support for Java 9 was improved in Gradle 4.x and that version is being used. Due to some issues with newer Gradle versions (#1198) some other configuration changes were required. As well as JaCoCo version has been bump (https://travis-ci.org/mockito/mockito/jobs/284996316#L799-L816).

Fixes #1198.

## Check list

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/2.x/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by szpak** [comment]
Rather yes. One of the failing tests in #1041 is the one I fixed. In addition master hasn't been built for a while and may be broken with the current Java 9.

**Comment by TimvdLippe** [comment]
@szpak I would like to revert this PR as it seems to break local development. I am facing various issues like:

<details>
```> Task :inline:test
Process 'Gradle Test Executor 31' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 31' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:382)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:118)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:41)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:74)
        at sun.reflect.GeneratedMethodAccessor700.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy93.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:215)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:327)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:103)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:83)
        at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Process 'Gradle Test Executor 32' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 32' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:382)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:118)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:41)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:74)
        at sun.reflect.GeneratedMethodAccessor700.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy93.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:215)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:327)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:103)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:83)
        at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

Failed to execute org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker@4c508c7.
java.lang.IllegalStateException: Some child operations have not yet completed.
        at org.gradle.internal.work.DefaultWorkerLeaseService$DefaultWorkerLease.releaseLock(DefaultWorkerLeaseService.java:350)
        at org.gradle.internal.resources.AbstractTrackedResourceLock.unlock(AbstractTrackedResourceLock.java:60)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService$ReleaseLocks.transform(DefaultResourceLockCoordinationService.java:213)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService$ReleaseLocks.transform(DefaultResourceLockCoordinationService.java:203)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:628)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
```
</details>
As well as internal compilation errors with the gradle scan plugin. It seems that Gradle 4 is breaking a lot of stuff, while Gradle 3.5 is working fine. Are you okay with reverting for now to then investigate what is going on?

**Comment by szpak** [comment]
@TimvdLippe Strange, it works on Travis as well as on my computer :). Do command do you call? What OS and Java version do you have?

**Comment by TimvdLippe** [comment]
I have tried with both openJDK8 and 9 on Ubuntu 16.04. It fails on `./gradlew clean build` on `release/2.x` and also when I try to merge `release/2.x` into `backport-fixes`

**Comment by szpak** [comment]
I'm not able to reproduce that issue. @szczepiq @raphw @ChristianSchwarz are you able to execute `./gradlew clean build` on `release/2.x`?

**Comment by TimvdLippe** [comment]
@szpak are you using openjdk or oracljedk? That's the only difference I can spot with my setup and Travis

**Comment by szpak** [comment]
OpenJDK on Fedora 26:

```
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

I have just also tested it with Oracle Java 9 (which after changes in the final version seems to be reported as OpenJDK as well):

```
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)
```

**Comment by TimvdLippe** [comment]
Hm, I have the latest available (on Ubuntu 16.04) JDK 8 version, which is 131. Maybe that is an issue?! Would be really weird that would trigger these errors.

**Comment by TimvdLippe** [comment]
I installed oraclejdk8 and it is working locally again. Probably a corrupt state of my computer which was resolved later. Glad it is working again :relieved:

**Pull request merged**
