### PR TITLE
Add support for answerClass in @Mock

### PR DESCRIPTION
**Pull request by scubbo**
See [this issue](https://code.google.com/p/mockito/issues/detail?id=345).

All credit for this change goes to kretes@, who actually authored it and created the [initial PR](https://github.com/mockito/mockito/pull/40) - I simply attended to the review comments and resubmitted since it appeared to have lain dormant for over a year.

### CODE REVIEW

**Comment by bric3** [comment]
I wonder if this is really necessary the following proposal 

``java
@Mock(answerClass = `WhateverAnswer.class`) SomeType mocked;
```

can be easily replaced with the more powerful `mock` factory method, and it supports answer injection as well.

```java
SomeType mocked = mock(SomeType.class, new WhateverAnswer())
```

**Comment by scubbo** [comment]
Sure - I agree that this functionality is already present in the factory method `mock` - that was precisely the motivation for this change, to bring `@Mock`'s functionality into line with `mock`'s.

**Comment by bric3** [comment]
Yeah but that makes the feature more limited when used with `@Mock` annotation. I'm kinda wary to just bring the answer **class** in the annotation ; if we find a better way later on then we'll have to live with that API.

**Comment by TimvdLippe** [comment]
I would prefer to keep the annotation as simple as possible. If additional features are required, `Mockito.mock()` should be used. Therefore closing this pull request.

**Pull request closed without merging**
