### PR TITLE
README.md release FAQ newlines

### PR DESCRIPTION
**Pull request by mureinik**
Add newlines between questions and answers in the FAQ of "How to release new version?" at the end of README.md to make it easier to read.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Instead of `<br>` can't we use normal newlines, but indent the next line?

**Comment by mureinik** [comment]
@TimvdLippe let me play around with it and see how it looks.

**Comment by mureinik** [comment]
@TimvdLippe It doesn't seem to render correctly unless I misunderstood your intent. See my attempt at https://github.com/mureinik/mockito/tree/README-tryout

**Comment by TimvdLippe** [comment]
This should work:

```
* Q My question

  A My answer
```

* Q My question

  A My answer
* Q My question

  A My answer
* Q My question

  A My answer

**Comment by mureinik** [comment]
Thought about it, but didn't like the way if it rendered. If you like the way it looks, I can definitely do that.

**Comment by TimvdLippe** [comment]
I prefer this format yes :smile:

**Comment by mureinik** [comment]
@TimvdLippe no problem, updated PR pushed for your review.

**Comment by szczepiq** [comment]
Nice! Thank you ;)

**Pull request merged**
