### PR TITLE
Mark reified varargs parameter @Deprecated

### PR DESCRIPTION
**Pull request by bjmi**
see title

### CODE REVIEW

**Comment by TimvdLippe** [comment]
How does this show up in your Idea? I understand we rely on the magic of the compiler to determine the type of the generic argument, but I didn't know you could annotate individual arguments as deprecated. Can you share a screenshot of a usage to show the UX?

**Comment by bjmi** [comment]
Currently IntelliJ IDEA and Eclipse IDE simply ignore the @Deprecated annotation when used on parameters.

But the intention to keep end users from passing a parameter value still applies.
> A program element annotated `@Deprecated` is one that programmers are discouraged from using, typically because it is dangerous, or because a better alternative exists. Compilers warn when a deprecated program element is used or overridden in non-deprecated code. - [Javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/Deprecated.html)

More information in this [SO answer](https://stackoverflow.com/a/14627381).

What do you think? :)

**Comment by TimvdLippe** [comment]
Since this annotation will not show up in either tooling or the compiler itself, I don't see a lot of use for adding it. When the compiler does emit a warning when a parameter is passed into such a method, I do see the value in adding it. For now, I am inclined to not merge this change. WDYT?

**Comment by bjmi** [comment]
> Since this annotation will not show up in either tooling or the compiler itself, I don't see a lot of use for adding it. When the compiler does emit a warning when a parameter is passed into such a method, I do see the value in adding it. For now, I am inclined to not merge this change. WDYT?

Could you please wait for the outcome of [IDEA-352253](https://youtrack.jetbrains.com/issue/IDEA-352253/Inspection-highlight-use-of-deprecated-parameter)? If it is implemented then the use of avoiding user errors is increased. Otherwise this PR has no real added value.

**Comment by bjmi** [comment]
The proposal in [IDEA-352253](https://youtrack.jetbrains.com/issue/IDEA-352253/Inspection-highlight-use-of-deprecated-parameter) is almost rejected.
This pull request can therefore also be closed.
Thank you for waiting.

**Comment by TimvdLippe** [comment]
Thanks for the update! We can reconsider when IDE's do support this.

**Pull request closed without merging**
