### PR TITLE
Backport fixes of release/2.x to master

### PR DESCRIPTION
**Pull request by TimvdLippe**
Yeah, we did this quite some time ago and this merge was hell. I hope I did not screw anything up. There are still 7 test failures, but I have to get dinner now. Please review this PR very carefully, to make sure I did not introduce regressions into master :sob:

### CODE REVIEW

**Comment by szpak** [comment]
@TimvdLippe Why there is just one commit in this PR? It makes harder to determine later on what changes/commits were already merged.

**Comment by TimvdLippe** [comment]
I did it in the same manner as you did in #861

**Comment by szczepiq** [comment]
Thank you guys for working on backporting!

**Comment by TimvdLippe** [comment]
Okay, looking at the Travis logs:

- We need to remove AnimalSniffer on `master` (https://travis-ci.org/mockito/mockito/jobs/222834587#L564)
- There are some regressions regarding varargs matching, maybe related to matching in java 8 (https://travis-ci.org/mockito/mockito/jobs/222834589#L584)
- Possibly an issue with ByteBuddy on Java 9? 😓 (https://travis-ci.org/mockito/mockito/jobs/222834589#L710) CC @raphw 
- Need to not hardcode jdk version, since Java 9 uses a different format (https://travis-ci.org/mockito/mockito/jobs/222834589#L717)
- Error I do not know what is causing it (https://travis-ci.org/mockito/mockito/jobs/222834589#L727)
- Maybe a flaky test, don't see it in a different build (https://travis-ci.org/mockito/mockito/jobs/222834588#L567)

**Comment by TimvdLippe** [comment]
I'll take another stab at this soon. The longer we wait, the worse the merge gets.

**Comment by TimvdLippe** [comment]
All right, the log has gotten pretty nasty, even though I just did `git merge` locally :sob: but most of the updates have been fixed. The only test that now fails is

```
org.mockito.internal.stubbing.answers.ThrowsExceptionTest > should_throw_mock_exception_without_stacktrace FAILED
    org.junit.ComparisonFailure: [no stack trace, it's mock] expected:<null> but was:<[]>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.mockito.internal.stubbing.answers.ThrowsExceptionTest.should_throw_mock_exception_without_stacktrace(ThrowsExceptionTest.java:35)
```
This might be a JDK issue, but I have no clue why it is suddenly failing.

**Comment by TimvdLippe** [comment]
@szpak Nice job, seems we got the build passing 🎉 I still need to figure out how to get Mockito working locally, but this PR is approved nonetheless 😄

**Comment by szpak** [comment]
I took a look at that and in the first case (a stacktrace) there was a change in your merge that cause a build to fail. Maybe the behavior is different when compiled against Java 8 and Java 6. I don't know. I reverted to the behavior from master.
I also bump build scan to the latest version to get better Gradle 4 compatibility.
My recent changes from master fixed the remaining failing test.

To sum it up. I will not venture to review the whole change set. On the other hand probably no-one will do that - there are just too many changes. Probably the best we can do it do merge it and fix potential problems in the future. In you agree feel free to merge it as will (IMHO, but you can also ask others to share the responsibility with them :) )

**Comment by TimvdLippe** [comment]
It is probably fine to merge as-is, as I mainly resolved merge conflicts. We can fix potential problems on master later.

**Pull request merged**
