### PR TITLE
Removing new line in bottom script. it seems that javadoc…

### LINKED ISSUE #256: task mockitoJavadoc fails when compiling in windows
When compiling the mockito project using gradle in a command line in Windows following compile error occurs:

javadoc: error - Illegal package name: "<script"
javadoc: error - Illegal package name: "type="
javadoc: error - Illegal package name: "text/javascript"
javadoc: error - Illegal package name: "src="
javadoc: error - Illegal package name: "{@docRoot}/js/jdk6-project-version-insert.js"
javadoc: error - Illegal package name: "></script>"
javadoc: error - Illegal package name: "<script"
javadoc: error - Illegal package name: "type="
javadoc: error - Illegal package name: "text/javascript"
javadoc: error - Illegal package name: "src="
javadoc: error - Illegal package name: "{@docRoot}/js/jquery-1.7.min.js"
javadoc: error - Illegal package name: "></script>"
javadoc: error - Illegal package name: "<script"
javadoc: error - Illegal package name: "type="
javadoc: error - Illegal package name: "text/javascript"
javadoc: error - Illegal package name: "src="
javadoc: error - Illegal package name: "{@docRoot}/js/highlight-8.6-java/highlight.pack.js"
javadoc: error - Illegal package name: "></script>"
javadoc: error - Illegal package name: "<link"
javadoc: error - Illegal package name: "rel="
javadoc: error - Illegal package name: "type="
javadoc: error - Illegal package name: "text/css"
javadoc: error - Illegal package name: "href="
javadoc: error - Illegal package name: "{@docRoot}/js/highlight-8.6-java/styles/obsidian.css"
javadoc: error - Illegal package name: "/>"
javadoc: error - Illegal package name: "<script"
javadoc: error - Illegal package name: "type="
javadoc: error - Illegal package name: "text/javascript"
javadoc: error - Illegal package name: ">"
javadoc: error - Illegal package name: "="
javadoc: error - Illegal package name: "&&"
javadoc: error - Illegal package name: "parseInt($.browser.version)"
javadoc: error - Illegal package name: "<"
javadoc: error - Illegal package name: "9;"
javadoc: error - Illegal package name: "if(!usingOldIE)"
javadoc: error - Illegal package name: "{"
javadoc: error - Illegal package name: "$("
javadoc: error - Illegal package name: ").append("
javadoc: error - Illegal package name: "<link rel=\"
javadoc: error - Illegal package name: "icon\\"
javadoc: error - Illegal package name: " href=\"
javadoc: error - Illegal package name: "{@docRoot}/favicon.ico?v=cafebabe\\"
javadoc: error - Illegal package name: ">"
javadoc: error - Illegal package name: ")"
javadoc: error - Illegal package name: "$("
javadoc: error - Illegal package name: ","
javadoc: error - Illegal package name: "window.parent.document).append("
javadoc: error - Illegal package name: "<link rel=\"
javadoc: error - Illegal package name: "icon\\"
javadoc: error - Illegal package name: " href=\"
javadoc: error - Illegal package name: "{@docRoot}/favicon.ico?v=cafebabe\\"
javadoc: error - Illegal package name: ">"
javadoc: error - Illegal package name: ")"
javadoc: error - Illegal package name: "hljs.initHighlightingOnLoad();"
javadoc: error - Illegal package name: "injectProjectVersionForJavadocJDK6("
javadoc: error - Illegal package name: "Mockito 2.0.29-beta API"
javadoc: error - Illegal package name: ","
javadoc: error - Illegal package name: "em#mockito-version-header-javadoc7-header"
javadoc: error - Illegal package name: ","
javadoc: error - Illegal package name: "em#mockito-version-header-javadoc7-footer"
javadoc: error - Illegal package name: ");"
javadoc: error - Illegal package name: "}"
javadoc: error - Illegal package name: "</script>"
javadoc: error - Illegal package name: ""
javadoc: warning - No source files for package stylesheet
javadoc: warning - No source files for package var
javadoc: warning - No source files for package usingOldIE
javadoc: warning - No source files for package $.browser.msie
javadoc: warning - No source files for package head
javadoc: warning - No source files for package shortcut
javadoc: warning - No source files for package head
javadoc: warning - No source files for package shortcut
64 errors
8 warnings

I tracked the issue down to gradle/javadoc.gradle where the gradle scripts sets the bottom property to a java script with multiple lines. 

Changing that to a single line seems to be make it possible to complete the mockitoJavaDoc task without any errors.

### PR DESCRIPTION
**Pull request by mat013**
… on windows are considering each new line as an argument rather than considering the entire parameter as an argument

The fix that BRIC13 applied in relation to https://github.com/mockito/mockito/issues/256. Did not resolve the issue I have submitted an alternative suggestion, which seems to be working (At least it worked on my machine :p)

### CODE REVIEW

**Comment by bric3** [comment]
ok I'd rather not do what you propose this way then. Which version of JDK are you running exactly ?

**Comment by mat013** [comment]
Hi Brice

I am running java 8 build 45.

Br

Meang

**Comment by bric3** [comment]
OK, I'll see what can be done, inlining this script here really hurts readability.

**Comment by bric3** [comment]
Fixed by #342

**Pull request closed without merging**
