### PR TITLE
Upgrade byte buddy to 1.10.5

### LINKED ISSUE #1841: Update byte-buddy to 1.10.5
Hi,

Byte-buddy had a bug that prevented running tests in IntelliJ due to space in the executable name: https://github.com/raphw/byte-buddy/issues/732 This was fixed in [1.10.5](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.10.5) so it would make sense to update it in Mockito as well.

### PR DESCRIPTION
**Pull request by villesau**
check list

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

Fixes #1841 

Byte buddy had a bug that prevented running tests in IntelliJ that's now fixed.

### CODE REVIEW

**Comment by villesau** [comment]
@TimvdLippe any chance of releasing this?

**Comment by TimvdLippe** [comment]
@villesau This has been released on Bintray: https://bintray.com/mockito/maven/mockito-development/3.1.13

**Comment by villesau** [comment]
@TimvdLippe looks like it's still not visible in github releases: https://github.com/mockito/mockito/releases

**Comment by TimvdLippe** [comment]
Yeah Mockito 3.2.1 was incorrectly tagged. Fixed in https://github.com/mockito/mockito/commit/4c290611c264adb917d935ec959f92acbcabdcd3

**Comment by villesau** [comment]
Great, thanks for the help @TimvdLippe! :)

**Comment by villesau** [comment]
@TimvdLippe one question still: Why it's not released in maven yet? https://mvnrepository.com/artifact/org.mockito/mockito-core/3.2.0

**Comment by TimvdLippe** [comment]
@villesau please see the explanation in the README: https://github.com/mockito/mockito/blob/release/3.x/README.md#how-to-release-new-version

**Pull request merged**
