### PR TITLE
Adding examples to explain inconsistent behaviour with TestNG

### PR DESCRIPTION
**Pull request by yuranos87**
Hi,

This is just an example requested long time ago in scope of: #810
This code is not to be merged but rather to provide another showcase. We can think of a potential solution together if you don't have one already.
Please, take a look - @bric3, @TimvdLippe

> Hey, 
> 
> Thanks for the contribution, this is awesome.
> As you may have read, project members have somehow an opinionated view on what and how should be
> Mockito, e.g. we don't want mockito to be a feature bloat.
> There may be a thorough review, with feedback -> code change loop.
> 
> Which branch : 
> - On mockito 2.x, make your pull request target `release/2.x`
> - On next mockito version make your pull request target `master`
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/PULL_REQUEST_TEMPLATE.md`

check list

 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/2.x/.github/CONTRIBUTING.md)
 - [ ] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [ ] Avoid other runtime dependencies
 - [ ] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [ ] The pull request follows coding style
 - [ ] Mention `Fixes #<issue number>` in the description _if relevant_
 - [ ] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Thank you for these tests! Is my conclusion correct that the workaround is to specify `@RunWith(MockitoJUnitRunner.class)`? Maybe instead of fixing, we should clearly document this behavior.

**Comment by yuranos87** [comment]
@TimvdLippe, the problem is with TestNG. Even if placing JUnit runner on top of TestNG test can do as a workaround, it's not a very good one.

**Comment by yuranos87** [comment]
@TimvdLippe , so where are we with this one? What's the final decision?

**Comment by TimvdLippe** [comment]
Sadly the Mockito developers have IRL conflicting activities, which means we have to strictly prioritize. Sadly TestNG is not on the top of our list, we are still focusing on Mockito 2.x integration and Android bug fixes

**Comment by yuranos87** [comment]
I would be happy to help if we agree on what to do at the very least. Are you planning to disallow nested @InjectMock in Mockito 2.x. If so, it makes sense to fix, otherwise, as you suggested, documenting it will do.

**Comment by TimvdLippe** [comment]
I think we should add documentation to InjectMocks, stating that it is rudimentary and not a full fledged injection framework. Then we have to accept it is a given :(

Thanks for your effort though! Sorry if this bug was very troubling for you.

**Comment by TimvdLippe** [comment]
Closing this one for now. Feel free to open a new PR to address the documentation changes @yuranos87

**Pull request closed without merging**
