### PR TITLE
New opt-in stubbing strictness implemented in JUnit rules

### PR DESCRIPTION
**Pull request by szczepiq**
New API (for rationale, see #769, for code review history see #770):

```java
//Existing API:
@Rule public MockitoRule mockito = MockitoJUnit.rule()

//Proposed improvements:
rule().strictness(Strictness.LENIENT)
rule().strictness(Strictness.WARN)       // <-- is the default
rule().strictness(Strictness.STRICT_STUBS)  // <-- Mockito 3.0 default
```

What "strict stubbing" means?
- Improved debuggability: the test fails early when code under test invokes stubbed method with different arguments.
- Cleaner tests without unnecessary stubbings: the test fails when there are any unused stubs declared.
- Cleaner, more DRY tests ("Don't Repeat Yourself"): If you use Mockito.verifyNoMoreInteractions() you no longer need to explicitly verify stubbed invocations. They are automatically verified.

For background and motivation, check out [Szczepan's article on LinkedIn](https://www.linkedin.com/pulse/curious-how-get-even-cleaner-tests-new-mockito-features-faber).

### CODE REVIEW

**Comment by TimvdLippe** [comment]
With interactive rebase you can squash commits away, or use `git reset --soft HEAD~2` to reset the last 2 commits :smile:

**Comment by szczepiq** [comment]
Thanks for the hint on slack about "git push -f". I could have used it to fix the original PR :)

**Comment by Stephan202** [comment]
For extra safety, prefer `git push --force-with-lease` :)

**Comment by bric3** [comment]
Agreed with @TimvdLippe it's simplier if you rebase interractively on your machine then push force-with-lease ;)

**Pull request merged**
