### PR TITLE
Fixes #2786: Add unequal arguments positions in failed verification message

### LINKED ISSUE #2786: If verify fails because of inequal arguments, highlight the wrong values
I use mockito a lot. But I just lost quite some time again, because I have overseen a detail in the out put of a failing verify.
A simple example:

```
@ExtendWith(MockitoExtension.class)
public class ExampleTest {
    @Mock
    TestObject testObject;

    @Captor
    ArgumentCaptor<Consumer<?>> captor;

    @Test
    void test() {
        Consumer<?> consumer = obj -> {};
        String myComplicatedString = "asdknasodinsafERFgIdfD334D";
        testObject.doStuff(myComplicatedString, consumer);

        verify(testObject).doStuff(eq("asdknasodinsafERFgldfD334D"), captor.capture());
    }

    public static class TestObject {

        public void doStuff(String myString, Consumer<?> myConsumer) {
            // do stuff
        }
    }
}

```

the output of this test is
```
Argument(s) are different! Wanted:
testObject.doStuff(
    "asdknasodinsafERFgldfD334D",
    <Capturing argument>
);
-> at com.qumea.mobilitysense.apiservice.messaging.consumers.ExampleTest$TestObject.doStuff(ExampleTest.java:35)
Actual invocations have different arguments:
testObject.doStuff(
    "asdknasodinsafERFgIdfD334D",
    com.qumea.mobilitysense.apiservice.messaging.consumers.ExampleTest$$Lambda$5127/0x00000008028baf08@71ebb0f1
);
```
Seeing this, I most likely assume that something has to be wrong with my lambda capture. Altought the problem is the string, which contains a small L instead of a large i, which is very prone to oversee.

It would be very welcoming if the log could be more clear about which argument is wrong.
e.g.

```
Actual invocations have different arguments:
testObject.doStuff(
    "asdknasodinsafERFgIdfD334D",  <-- Unexpected value
    com.qumea.mobilitysense.apiservice.messaging.consumers.ExampleTest$$Lambda$5127/0x00000008028baf08@71ebb0f1
);
```

I think this would save a lot of time.

### PR DESCRIPTION
**Pull request by mathieufortin01**
I found this one useful (and an opportunity to dive into the code) since it also occurred to me in the past to be confused on which argument was unequal.

Tried to make it not too intrusive. Essentially it gives a hint on which argument positions are considered not matching. There are a few possible cases:
1. Single arg method: same as before as the culprit is pretty clear
2. Single arg not matching: `Actual invocations have different arguments at position [0]:`
3. Multiple args not matching: `Actual invocations have different arguments at positions [0, 1]:`

The example from the issue would become (notice the _at position [0]_ added):
```
Argument(s) are different! Wanted:
testObject.doStuff(
    "asdknasodinsafERFgldfD334D",
    <Capturing argument>
);
-> at com.qumea.mobilitysense.apiservice.messaging.consumers.ExampleTest$TestObject.doStuff(ExampleTest.java:35)
Actual invocations have different arguments at position [0]:
testObject.doStuff(
    "asdknasodinsafERFgIdfD334D",
    com.qumea.mobilitysense.apiservice.messaging.consumers.ExampleTest$$Lambda$5127/0x00000008028baf08@71ebb0f1
);
```

Let me know if this is an adequate solution, or if you dont intend to add something like this.

## Checklist

 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [ ] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [ ] Avoid other runtime dependencies
 - [ ] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [ ] The pull request follows coding style
 - [ ] Mention `Fixes #<issue number>` in the description _if relevant_
 - [ ] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Yeah I think this would be a useful addition! Seems like we have 5 test failures though that matched on the original string.

**Review by TimvdLippe — APPROVED** [review]
Thank you!

**Comment by TimvdLippe** [comment]
Oh there are conflicts 😅

**Comment by mathieufortin01** [comment]
> Oh there are conflicts 😅

Yeah because of the one just merged. Fixing that.

**Pull request merged**
