### PR TITLE
Update gradle (v4.9) and shipkit (v2.0.28)

### PR DESCRIPTION
**Pull request by epeee**
I did some local testing using dryRun:

```
...
> Task :bintrayUpload
Task ':bintrayUpload' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:bintrayUpload - publishing to Bintray
  - dry run: true, publish: true, version: 2.19.5, Maven Central sync: false
  - user/org: szczepiq/mockito, repository/package: maven/mockito-development
Gradle Bintray Plugin version: 1.8.3
Uploading to https://api.bintray.com/content/mockito/maven/mockito-development/2.19.5/org/mockito/mockito-core/2.19.5/mockito-core-2.19.5-sources.jar...
(Dry run) Uploaded to 'https://api.bintray.com/content/mockito/maven/mockito-development/2.19.5/org/mockito/mockito-core/2.19.5/mockito-core-2.19.5-sources.jar'.
Uploading to https://api.bintray.com/content/mockito/maven/mockito-development/2.19.5/org/mockito/mockito-core/2.19.5/mockito-core-2.19.5-javadoc.jar...
(Dry run) Uploaded to 'https://api.bintray.com/content/mockito/maven/mockito-development/2.19.5/org/mockito/mockito-core/2.19.5/mockito-core-2.19.5-javadoc.jar'.
Uploading to https://api.bintray.com/content/mockito/maven/mockito-development/2.19.5/org/mockito/mockito-core/2.19.5/mockito-core-2.19.5.jar...
(Dry run) Uploaded to 'https://api.bintray.com/content/mockito/maven/mockito-development/2.19.5/org/mockito/mockito-core/2.19.5/mockito-core-2.19.5.jar'.
Uploading to https://api.bintray.com/content/mockito/maven/mockito-development/2.19.5/org/mockito/mockito-core/2.19.5/mockito-core-2.19.5.pom...
(Dry run) Uploaded to 'https://api.bintray.com/content/mockito/maven/mockito-development/2.19.5/org/mockito/mockito-core/2.19.5/mockito-core-2.19.5.pom'.
:bintrayUpload (Thread[Task worker for ':',5,main]) completed. Took 0.009 secs.
:bintrayPublish (Thread[Task worker for ':' Thread 3,5,main]) started.

> Task :bintrayPublish
Task ':bintrayPublish' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
(Dry run) Signed version 'mockito/maven/mockito-development/2.19.5'.
(Dry run) Published version 'mockito/maven/mockito-development/2.19.5'.
(Dry run) Signed version 'mockito/maven/mockito-development/2.19.5'.
(Dry run) Published version 'mockito/maven/mockito-development/2.19.5'.
(Dry run) Signed version 'mockito/maven/mockito-development/2.19.5'.
(Dry run) Published version 'mockito/maven/mockito-development/2.19.5'.
(Dry run) Signed version 'mockito/maven/mockito-development/2.19.5'.
(Dry run) Published version 'mockito/maven/mockito-development/2.19.5'.
:bintrayPublish (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 0.014 secs.
```

### CODE REVIEW

**Comment by epeee** [comment]
This one is not ready yet. It looks like my local maven cache did already contain a mockito-core artifact and therefore the local build was passing.
I will continue working on this one later on today.

**Comment by epeee** [comment]
This pr is ready for review now.

**Comment by mockitoguy** [comment]
Let's give it a shot. Thank you!

**Comment by epeee** [comment]
hmm, just saw this one in the travis ci log:

```
[releaseNeeded] > Task :downloadPreviousReleaseArtifacts
[releaseNeeded]   Downloading remote artifact
[releaseNeeded]   - from https://bintray.com/mockito/maven/download_file?file_path=org/mockito/mockito-mockito/2.19.6/mockito-mockito-2.19.6-sources.jar
[releaseNeeded]   - and saving it to /home/travis/build/mockito/mockito/build/previous-release-artifacts/mockito-core-2.19.6-sources.jar
[releaseNeeded]   Unable to download, ignoring. Run with '-d' for stack trace.
[releaseNeeded]    If the download URL is incorrect you may need to configure the URL manually.
[releaseNeeded]   See DownloadPreviousPublicationTask for details.
[releaseNeeded]   Url: https://bintray.com/mockito/maven/download_file?file_path=org/mockito/mockito-mockito/2.19.6/mockito-mockito-2.19.6-sources.jar
[releaseNeeded] 
[releaseNeeded] > Task :createDependencyInfoFile UP-TO-DATE
[releaseNeeded] > Task :sourcesJar UP-TO-DATE
```

the download url for the previous mockito-core artifact does not look good, I will have a look at it later on today.

**Pull request merged**
