### PR TITLE
Fixes #194 tweaks any matchers

### LINKED ISSUE #194: Tweaks Matchers.any family matchers behavior
This issue is a follow up of the work started in #141 by @pimterry. Also here's an extract of a message on [this thread](https://groups.google.com/forum/#!topic/mockito/8_WGBB3Jbtk) of the mailing list :

-------------

The origin of these methods is they come from `anything` i.e. anything matches, later for shortness and cast avoidance the aliases grew, but the API naming thus became inconsistent with what a human would expect. So this behavior is being changed in mockito 2 beta, to be precise here's the status on these API in the version 2.0.5-beta :

- `any`, `anyObject`, `any(Class)` won't check anything (at first they were just aliases for _anything_ and for cast avoidance), `null` is a valid value
- `anyX` like `anyString` will check the arg is not `null` and that has the correct type
- `anyList` will check the argument is not null and a `List` instance
- `anyListOf` (and the likes) at the moment are just aliases to their non generic counter part like `anyList`

Note this is work in progress (started here in [#141](https://github.com/mockito/mockito/pull/141)), these new behavior can / will change in the beta phase. I'm especially wondering if the `any` family should allow `null` and if not do a type check. For example with these matchers : 

- `any`, `anyObject` stay the same, they currently allow `null` and don't have to do type check anyway
- `any(Class)` currently allows `null` and doesn't do type check => allows `null` and if not checks for the given type
- `any<Collection>Of` currently doesn't allow `null` and does a type check of the collection, not elements => allows `null`, if not checks collection type, if not empty checks element type

Maybe extend/create a _symmetric_  `isA` family API that won't allow any `null` arguments.

-------------

### PR DESCRIPTION
**Pull request by bric3**
Details is #194 

I took the opportunity to 

* replace `TestBase.assertThat` by more powerful AssertJ equivalent. There's still some work to be done in this class.
* add iterable matchers

Before merging

* [ ] I ponder to make `anyObject()` not to accept `null`, currently `any()` is an alias of `anyObject()`
* [x] I need to update `anyInt` family description.

### CODE REVIEW

**Comment by bric3** [comment]
Here's some poll on twitter :

https://twitter.com/BriceDutheil/status/758967944881639424
https://twitter.com/BriceDutheil/status/758969135489388544

**Comment by bric3** [comment]
30 votes and I merge the PR, I'll monitor the poll after my holidays

**Comment by Stephan202** [comment]
If I understand correctly `List<T> anyListOf(Class<T> clazz)` was deprecated in favour of `List anyList()`. Shouldn't the latter then be made generic? When I replace one with the other I get "unchecked conversion" warnings.

**Comment by bric3** [comment]
@Stephan202 thanks for the feedback, yes it was deprecated for people that use Java8 as documented in the javadoc. And the deprecation announces removal in Mockito 3 which will be Java 8 minimum.

**Comment by Stephan202** [comment]
@bric3: I am on Java 8 and did migrate as suggested. I agree this is a change for the better :).

My point is that this replaces a deprecation warning with an unchecked conversion warning. The question is, shouldn't the following type of change be applied to all aforementioned methods?
```diff
--- a/src/main/java/org/mockito/ArgumentMatchers.java
+++ b/src/main/java/org/mockito/ArgumentMatchers.java
@@ -474,9 +474,9 @@ public class ArgumentMatchers {
      * @see #isNull()
      * @see #isNull(Class)
      */
-    public static List anyList() {
+    public static <T> List<T> anyList() {
         reportMatcher(new InstanceOf(List.class, "<any List>"));
-        return new ArrayList(0);
+        return new ArrayList<T>(0);
     }
```

**Comment by bric3** [comment]
> shouldn't the following type of change be applied to all aforementioned methods?

What do you mean by that ?

> this replaces a deprecation warning with an unchecked conversion warning

Do you mean that IDEs show an unchecked conversion when using `anyList()`

**Comment by Stephan202** [comment]
> > shouldn't the following type of change be applied to all aforementioned methods?

> What do you mean by that ?

I'm not sure what more to explain: the diff shows the addition of a generic type argument to `ArgumentMatchers#anyList`. I propose this change is made to said method, as well as `ArgumentMatchers#{anySet,anyMap,anyCollection,anyIterable}`.

> > this replaces a deprecation warning with an unchecked conversion warning

> Do you mean that IDEs show an unchecked conversion when using anyList()

My compiler does, and we compile with `-Werror`. Sure, I can suppress the warning on our side, but the changes I'm proposing is in line with `ArgumentMatchers#any`, so it seems to "make sense".

**Comment by bric3** [comment]
Oh thanks it seems I forgot to stash these lines. I thought it was in the commit !
I'm fixing that right now.

**Comment by Stephan202** [comment]
Cool :)

**Comment by bric3** [comment]
See #528

**Pull request merged**
