### PR TITLE
Enable container based infrastructure on Travis

### PR DESCRIPTION
**Pull request by szpak**
To verify it works and is faster.

DO NOT MERGE (YET)

### CODE REVIEW

**Comment by TimvdLippe** [comment]
So thats a nope and a bummer :(

**Comment by bric3** [comment]
Yep still the same thing :

https://travis-ci.org/mockito/mockito/jobs/152623206#L354

```
> Process 'Gradle Test Executor 3' finished with non-zero exit value 137
```

**Comment by bric3** [comment]
Nice idea to increase memory.

Not sure it's way faster though

* Before https://travis-ci.org/mockito/mockito/builds/152633515 ~ 2min
* After https://travis-ci.org/mockito/mockito/builds/152638526 ~ 2min

**Comment by bric3** [comment]
Why increasing test even more, 512 MB seems already quite huge for a lib like mockito.

**Comment by szpak** [comment]
@bric3 The build time for Java 8 is much higher. I'm testing if accidentally memory is not a limitation.

**Comment by bric3** [comment]
Oh OK

**Comment by szpak** [comment]
With @marcingrzejszczak we had the same problem with some other open source project. The remedy was to increase the amount of memory available for tests. It seems to help also in Mockito. The last 5 builds in that branch finished successfully - https://travis-ci.org/mockito/mockito/branches.

Btw, it's hard to compare reliably, but with `-Xmx768m` Java 8 build is faster than with 512m (while 512m seems to be enough to be not killed).

Unfortunately the overall build time seems to be similar. However, it seems to be the future of builds on Travis, so IMHO we could make a switch.

**Comment by szpak** [comment]
Created https://github.com/mockito/mockito/issues/563 for flaky test: ThreadsRunAllTestsHalfManualTest > shouldRunInMultipleThreads

**Comment by szpak** [comment]
Btw, https://travis-ci.org/mockito/mockito/jobs/152643498 failed due to my interactive rebase.

**Comment by bric3** [comment]
Maybe try with the tricks in this ticket : https://github.com/travis-ci/travis-ci/issues/3259

```yml
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
```

**Comment by bric3** [comment]
Not sure it's the cause of the problem, but that's a big difference that I'm spotting right now, between container based and bare metal

**Comment by szpak** [comment]
Yup, I've been using `oracle-java8-installer` yesterday. Works, but increased build time by ~20 seconds. It's bad that Travis doesn't provide recent Java 8 version by default.

**Comment by TimvdLippe** [comment]
Superseded by #785

**Pull request closed without merging**
