### PR TITLE
Update to OpenJDK 15.

### PR DESCRIPTION
**Pull request by raphw**
Use Java 15 in builds for most recent Java version.

### CODE REVIEW

**Review by TimvdLippe — APPROVED** [review]

**Comment by TimvdLippe** [comment]
Seems like we got some test failures :(

**Comment by raphw** [comment]
Needed to update Jacoco. Works now.

**Comment by raphw** [comment]
Strangely enough, it builds locally. Will investigate some more!

**Comment by raphw** [comment]
It's weird, if I build locally with the same command and Java version (build and major), I cannot reproduce this error...

**Comment by TimvdLippe** [comment]
I don't think I have Java 15 installed on any of my machines and not sure if I can get a hold of them. Looking at the test failures, many of them seem related to how we handle `null` with primitive matchers. Is there some way to check the changelog to see if we see any suspicious changes?

**Comment by raphw** [comment]
I ran the exact build version locally and it works, on a fresh clone even, also on Linux.

**Comment by Marcono1234** [comment]
I am seeing these failures for JDK 15 (build 15+36-1562) as well, but on Windows.
It looks like the cause for this is [JDK-8233014](https://bugs.openjdk.java.net/browse/JDK-8233014) which enables "Helpful NullPointerExceptions" by default.

The tests which are failing apparently make assumptions about how NullPointerExceptions look like, which are now not true anymore:
* https://github.com/mockito/mockito/blob/4d44781331fd57dda6c31cf1d70151ad04883e2a/src/test/java/org/mockitousage/stubbing/StubbingWithDelegateTest.java#L107
NullPointerException now mentions the name of the method which returned `null`:
  > java.lang.NullPointerException: Cannot invoke "java.lang.Byte.byteValue()" because the return value of "org.mockitousage.IMethods.byteObjectReturningMethod()" is null
* https://github.com/mockito/mockito/blob/4d44781331fd57dda6c31cf1d70151ad04883e2a/src/test/java/org/mockitousage/matchers/InvalidUseOfMatchersTest.java#L109
Assumes that NullPointerException has no message.
* https://github.com/mockito/mockito/blob/4d44781331fd57dda6c31cf1d70151ad04883e2a/src/test/java/org/mockitousage/serialization/DeepStubsSerializableTest.java#L85
Assumes that NullPointerExceptions has no message.

**Comment by TimvdLippe** [comment]
Thanks for the great investigation @Marcono1234 Do you mind creating a PR with the necessary fixes to make it work on JDK 15?

**Comment by Marcono1234** [comment]
I fear that I am not familiar enough with Mockito to perform these changes while still keeping the intended functionality for the tests.
For `StubbingWithDelegateTest` it looks like this could be simplified to checking whether the returned `Byte` is `null` instead of provoking the `NullPointerException`, is that correct? I assume for `DeepStubsSerializableTest` it is similar, it might already suffice to check whether `next()` returned `null`.
But for `InvalidUseOfMatchersTest` maybe the only solution would be to drop the requirement that the message must be `null`.

**Comment by raphw** [comment]
The requirement does not seem meaningful to me, at least. I just fixed the tests to not require an empty message.

**Review by Marcono1234 — COMMENTED** [review]
I might not be familiar enough with Mockito, but wouldn't it be possible for `StubbingWithDelegateTest` and `DeepStubsSerializableTest` to not provoke the `NullPointerException` at all (as outlined above), but instead test for a `null` return value?  That would probably make the tests more robust since they might otherwise catch unrelated NullPointerExceptions which are caused by bugs.

**Comment by raphw** [comment]
Good point, I just adjusted the tests.

**Review by TimvdLippe — APPROVED** [review]
Test changes LGTM.

**Pull request merged**
