### PR TITLE
Simplified ArgumentMatcherStorageImpl and logic matchers

### PR DESCRIPTION
**Pull request by ChristianSchwarz**
Simplified the classes `ArgumentMatcherStorageImpl`, `And`, `Or`and `Not `by removing code duplications and unnecessary logic, saving 50 lines of code.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
@ChristianSchwarz Could you rebase on master? The build issues should be fixed now

**Comment by bric3** [comment]
Not on `master`, but `release/2.x` ;)

**Comment by TimvdLippe** [comment]
Oops yes correct!

**Comment by szczepiq** [comment]
>saving 50 lines of code

I love it! :D Is this refactoring only, e.g. no observable behavior change?

**Comment by ChristianSchwarz** [comment]
> Is this refactoring only, e.g. no observable behavior change?
Yes, the behaviour is the same.

> Could you rebase on master? The build issues should be fixed now
I rebased, but still: assertEnvVariables FAILED

**Comment by szczepiq** [comment]
That's really awkward. Looks like a bug in Travis? If you look at the Travis CI settings (https://travis-ci.org/mockito/mockito/settings), clearly GH_TOKEN env variable is declared. Can someone look into why env variables declared in Travis don't make their way to the build environment?

**Comment by TimvdLippe** [comment]
Pushed to https://github.com/mockito/mockito/tree/matcher-stack If the build passes there I will merge it.

**Comment by TimvdLippe** [comment]
Manually merged in https://github.com/mockito/mockito/commit/e9d7534133ed66de9da302479291b669b2fa33b8 as the build passed on our branch (besides the SSL issue on JDK6)

**Pull request closed without merging**
