### PR TITLE
Fix thread race on invocationForStubbing

### LINKED ISSUE #2516: Thread race issue in `setInvocationForPotentialStubbing`
Internally at Google, we discovered a thread race on `setInvocationForPotentialStubbing`. A truncated stacktrace:

```
    #0 org.mockito.internal.stubbing.InvocationContainerImpl.setInvocationForPotentialStubbing(Lorg/mockito/invocation/MatchableInvocation;)V InvocationContainerImpl.java:47 
    #1 org.mockito.internal.handler.MockHandlerImpl.handle(Lorg/mockito/invocation/Invocation;)Ljava/lang/Object; MockHandlerImpl.java:86 
    #2 org.mockito.internal.handler.NullResultGuardian.handle(Lorg/mockito/invocation/Invocation;)Ljava/lang/Object; NullResultGuardian.java:29 
    #3 org.mockito.internal.handler.InvocationNotifierHandler.handle(Lorg/mockito/invocation/Invocation;)Ljava/lang/Object; InvocationNotifierHandler.java:34 
    #4 org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;Lorg/mockito/internal/invocation/RealMethod;Lorg/mockito/invocation/Location;)Ljava/lang/Object; MockMethodInterceptor.java:82 
    #5 org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;Lorg/mockito/internal/invocation/RealMethod;)Ljava/lang/Object; MockMethodInterceptor.java:56 
    #6 org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(Ljava/lang/Object;Lorg/mockito/internal/creation/bytebuddy/MockMethodInterceptor;Ljava/lang/reflect/Method;[Ljava/lang/Object;Ljava/util/ MockMethodInterceptor.java:145 
```

It raced with `resetInvocationForPotentialStubbing`:

```
    #0 org.mockito.internal.stubbing.InvocationContainerImpl.resetInvocationForPotentialStubbing(Lorg/mockito/invocation/MatchableInvocation;)V InvocationContainerImpl.java:51 
    #1 org.mockito.internal.handler.MockHandlerImpl.handle(Lorg/mockito/invocation/Invocation;)Ljava/lang/Object; MockHandlerImpl.java:120 
    #2 org.mockito.internal.handler.NullResultGuardian.handle(Lorg/mockito/invocation/Invocation;)Ljava/lang/Object; NullResultGuardian.java:29 
    #3 org.mockito.internal.handler.InvocationNotifierHandler.handle(Lorg/mockito/invocation/Invocation;)Ljava/lang/Object; InvocationNotifierHandler.java:34 
    #4 org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;Lorg/mockito/internal/invocation/RealMethod;Lorg/mockito/invocation/Location;)Ljava/lang/Object; MockMethodInterceptor.java:82 
    #5 org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;Lorg/mockito/internal/invocation/RealMethod;)Ljava/lang/Object; MockMethodInterceptor.java:56 
    #6 org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(Ljava/lang/Object;Lorg/mockito/internal/creation/bytebuddy/MockMethodInterceptor;Ljava/lang/reflect/Method;[Ljava/lang/Object;Ljava/util/ MockMethodInterceptor.java:145 
```

### PR DESCRIPTION
**Pull request by TimvdLippe**
Fixes #2516

### CODE REVIEW

**Comment by TimvdLippe** [comment]
@raphw do you mind taking a look? I think this is a low risk change and should eliminate all race conditions in this class.

**Comment by raphw** [comment]
Hmm, I would not know why this would be invoked from two different threads. Stubbing is not working if done from multiple threads as the call order is imprtant.

**Comment by TimvdLippe** [comment]
So I think the actual race is in a different location. When we handle an invocation, we first store the invocation here: https://github.com/mockito/mockito/blob/d5cad0648a454b237ee30f1a2b9919cf73fcee68/src/main/java/org/mockito/internal/handler/MockHandlerImpl.java#L86

Then we do some work and ultimately, we reset the invocation: https://github.com/mockito/mockito/blob/d5cad0648a454b237ee30f1a2b9919cf73fcee68/src/main/java/org/mockito/internal/handler/MockHandlerImpl.java#L120

The thread race report essentially boils down to:

1. Thread one invokes a method on a mock
2. Thread two invokes a method on a mock
3. Thread one sets the invocation for stubbing
4. Thread two sets the invocation for stubbing
5. Thread one resets the invocation for stubbing, before thread two could do anything
6. Thread two assumes that the stubbing that is set is the correct one, but it is actually reset already to the one from thread one

Rather than adding `synchronized` to the store, should we maybe wrap lines 86 until 122 of `MockHandlerImpl` in an `synchronized` block to avoid the race condition?

I am a bit surprised as to why this doesn't have any practical implications though. I am not aware of any multi-threaded tests at Google (which we have plenty of) that run into any issues.

**Comment by TimvdLippe** [comment]
Closing this as I don't think this is the correct fix.

**Pull request closed without merging**
