### PR TITLE
Fixes #2030 : DOCS Added reference to requirements to Java 8 support in Android

### LINKED ISSUE #2030: Documentation about Java 8 / MethodHandle in Android support
Hi guys!

Regarding this [Twitter thread ](https://twitter.com/rafaelcodes/status/1295298728367206403) with @raphw where Jake Wharton
mentions the requirements to better Java 8 support in Android. I suggest add a specific entry in the documentation about it.

Affected versions: Android with minSdk<26, Mockito v3.5.0

 - [X] The mockito message in the stacktrace have useful information, but it didn't help
 - [X] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [X] Provide versions (mockito / jdk / os / any other relevant information) 
 - [X] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by earth001**
Hi Guys

This is my first contribution here, let me know if this can be improved in some way.  

check list
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)
 - [X] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [X] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [X] Avoid other runtime dependencies
 - [X] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [X] The pull request follows coding style
 - [X] Mention `Fixes #<issue number>` in the description _if relevant_
 - [X] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by raphw** [comment]
We kind of resolved this but got stuck on the Objenesis version. I think the best way to address this is the fixation of the Objenesis version for the *mockito-android* bundle as suggested elsewhere.

**Comment by earth001** [comment]
Great @raphw. Do you refer to set the version in the to 'org.objenesis:objenesis:2.6' in the android module?

**Comment by raphw** [comment]
Yes, I think that's the way to go. Setting these requirements gives the wrong impression since it can be so easily avoided.

**Comment by earth001** [comment]
Ok, well, I think that with something like this it could be fixed:
In dependencies.gradle:
`libraries.objenesisCompatibleAndroid = '2.6'`
In android.gradle:
```
dependencies {
    compile project.rootProject
    compile libraries.bytebuddyandroid
    compile("org.objenesis:objenesis") {
        version {
            strictly libraries.objenesisCompatibleAndroid
        }
        because("MethodHandle class dependency breaks on Android with minSdkVersion<26")
    }
}
```
Also the output of ./gradlew -q dependencies for the android module show this:

```
compileClasspath - Compile classpath for source set 'main'.
+--- project :
|    +--- net.bytebuddy:byte-buddy:1.10.13
|    +--- net.bytebuddy:byte-buddy-agent:1.10.13
|    \--- org.objenesis:objenesis:3.1 -> 2.6
+--- net.bytebuddy:byte-buddy-android:1.10.13
|    +--- net.bytebuddy:byte-buddy:1.10.13
|    \--- com.jakewharton.android.repackaged:dalvik-dx:9.0.0_r3
\--- org.objenesis:objenesis:{strictly 2.6} -> 2.6

```
If you are ok with this, I can send it on a new PR.

**Comment by TimvdLippe** [comment]
@earth001 Thanks for your investigation! We have a PR open already (#2024) could you take a look at that? Also ping @raphw for reviewing that one, it is fine by me to be merged.

**Comment by earth001** [comment]
@TimvdLippe Thanks for pointing me that! also that PR looks more complete.  So, I think this PR is not needed.

If you like I can add a small reference to Java 8 requirements for Android in the previous paragraph, something like:

... on Android due to limitations in the Android VM ([See Java 8 support](https://developer.android.com/studio/write/java8-support)).  

If you think is not necessary I can close the PR instead.

**Comment by earth001** [comment]
Hi guys, I see the PR #2024 was already merged. What do you think about this one? 
In my point of view, It would be helpful to add a reference to the limitations of Java Android VM.

**Comment by TimvdLippe** [comment]
It is a well-known limitation of the Android VMs, so I don't think it is necessary. The build system should prevent users from building the project and they will see an explanatory message. I would therefore like to wait with adding additional documentation. If there is further confusion, we could add a clarifying message to our main documentation indeed.

**Comment by earth001** [comment]
Nice @TimvdLippe , so I close this one. Please let me know if there something I can help.

**Pull request closed without merging**
