### PR TITLE
Implements mocking for constructor invocations.

### PR DESCRIPTION
**Pull request by raphw**
Allows to declare all constructor invocations as mocking attempts.

### CODE REVIEW

**Comment by msteinbeck** [comment]
Are there any plans on when this will be released? I'm really looking forward for this feature.

**Comment by raphw** [comment]
Many of us are on vacation at the time but likely some time in August.

**Comment by JojOatXGME** [comment]
As far as I can see, there is still no support to get the arguments of the constructor. Is it planed to be added at some point? Here is a small motivation. I usually use copy constructors if I want to copy objects. (I think `clone()` is more or less broken.) If I want to assert that some mocked object is a copy of another object, I would need to look at the constructor arguments when the object is created.

Beside that, I think it would improve usability when `MockedConstruction` had a method to change the preparation callback. Otherwise, it is impossible to set a preparation callback when `@Mock` is used.

**Comment by raphw** [comment]
Good point, I refactored it to take a `Context` object in addition to the mock where one can get the invoked constructor including its arguments and an index for the count of the created mock for a given scope. This should offer any desired functionality.

**Comment by raphw** [comment]
Already on master.

**Pull request closed without merging**
