### PR TITLE
Fixes exception typo

### PR DESCRIPTION
**Pull request by MGaetan89**
This is a simple correction in an error message that can be thrown by Mockito.

### CODE REVIEW

**Comment by bric3** [comment]
@MGaetan89 Thanks

**Comment by bric3** [comment]
Can you rename the message commit, `Minor test fix` does not help when looking at the history.

Something like `Fixes exception typo in mockmaker` would do it.

**Comment by MGaetan89** [comment]
Sure, I will do it later.

**Comment by MGaetan89** [comment]
@bric3 Sorry for the delay. I updated the commit message.

**Comment by bric3** [comment]
@MGaetan89 No problem thanks for getting back ;)

**Pull request merged**
