### PR TITLE
Test case and fix for memory leak issue described in #1736

### PR DESCRIPTION
**Pull request by awillinger**
Added a testcase as wanted here: https://github.com/mockito/mockito/issues/1736#issuecomment-511144519

Please keep in mind that this test currently fails, as I did not work on a fix yet.
For more information, please see issue #1736.

### CODE REVIEW

**Comment by awillinger** [comment]
Build seems to be "correctly" failing now, as in, with an OOM because of the bug.

**Comment by awillinger** [comment]
Sorry for the delay, I only just now managed to leave from work early so I can take a look at this again.

The fix for the initial issue (the leak in the RunNotifier) is an easy one, just need to set aside some time to implement/test it.

Not sure how to proceed with the one occurring within the Suite Runner - see last comment in the linked issue.. would have to remove the final modifier from the runner and clear it as well when the run finishes, unless you got a better idea?

**Comment by TimvdLippe** [comment]
> unless you got a better idea

Sadly no :cry: Looking forward to your fix!

**Comment by awillinger** [comment]
Finally managed to get around fixing this problem. 

In the diff itself, you will see the following 3 main changes:
* An extension of the memory-test.gradle, explicitly excluding all classes whose name contain the string "TestDefinition". I had to add that, as otherwise, JUnit would execute the Suite AS WELL AS the test class in itself, so 3 times in total instead of twice. With this fix, the test class will only ever run if it is included explicitly within a test suite.
Interestingly, there appears to be a memory leak within JUnit Suite classes as well, as in this case (suite + test class itself) the runner would still be referenced through a "BeforeMethods"-class - out of focus for this issue.
More info: https://discuss.gradle.org/t/how-to-run-a-testsuite-but-not-the-test-classes-directly/14576
* The test case itself, as requested in the issue, whereas the test class itself is named "TestDefinition", to avoid running it outside the suite. This simply allocates a Long-array which uses up ~127.9MB of RAM.
* The fix itself. Instead of resetting the runner / making the field non-final, I decided to simply drop the "target" field entirely, and pass through the testClass-Class direcltry to the event, as the only usage of the "target" field was a call to Object#getClass - which is not needed, as JUnit passes in the to-be-run class already.
I still added the RunNotifier#removeListener call to make the call site "symmetric".

**Comment by mockitoguy** [comment]
I'll review this. Thank you!

**Comment by TimvdLippe** [comment]
I was about to merge this (great issue description and fix!) but sadly Travis is failing with ```org.mockito.memorytest.ShouldFreeMemoryAfterExecutionFinishedSuite > org.mockito.memorytest.ShouldFreeMemoryAfterExecutionFinishedTestDefinition.classMethod FAILED
    java.lang.OutOfMemoryError```

Could you take another look and find out if we need to make additional changes? Thanks and sorry for the slow response.

**Comment by awillinger** [comment]
Well, I did run a full Gradle build on my dev machine which completed successfully. Seems like only two of the environments (both JDK8s) are failing - one of which for an unrelated reason.

Is there a way to re-trigger Travis without actually pushing another commit? Maybe it got confused with the rebase-force-push shenanigans I was doing.

**Comment by TimvdLippe** [comment]
I have restarted the jobs. Lets see if they are still problematic

**Comment by TimvdLippe** [comment]
I am closing this PR for inactivity and Travis failures. Feel free to reopen once they are resolved 😄

**Pull request closed without merging**
