### PR TITLE
Started generating the release notes document to "v2.md" file.

### PR DESCRIPTION
**Pull request by szczepiq**
Let's not merge to master. Let's merge it to the release branch once it is ready. Preview-only PR.

### CODE REVIEW

**Comment by bric3** [comment]
OK

**Comment by TimvdLippe** [comment]
I do not see any changelog of Mockito 2 in v2.md?

**Comment by szczepiq** [comment]
Actaully, it will be cleaner to push notes to the same file location in each branch, eg each releasable barnch pushes to (in branch)/doc/release-notes/official.md

**Comment by bric3** [comment]
Agreed, with git and github this allows to switch branch on the file

**Comment by szczepiq** [comment]
Won't merge. We decided on a different strategy

**Comment by bric3** [comment]
@szczepiq huh what do you mean ?

**Comment by szczepiq** [comment]
Every branch will generate to the same location, e.g "official.md"

**Comment by bric3** [comment]
Ah OK.

**Pull request closed without merging**
