### PR TITLE
Fixes #358: Added custom capturing matcher to support conditional cap…

### LINKED ISSUE #358: Enhancement: ArgumentCaptor.captureIf(ArgumentMatcher)
Assume we have the following test.

```
 @Mock
 private Consumer<Collection<?>> consumer;

 @Test
 public void test() throws Exception {
       
    consumer.accept(new HashSet<>());
    consumer.accept(new ArrayList<>());
       
    ArgumentCaptor<ArrayList<?>> captor = ArgumentCaptor.forClass(ArrayList.class);
    verify(consumer).accept(captor.capture());
 }
```

The test fails with:
```
org.mockito.exceptions.verification.TooManyActualInvocations:
consumer.accept(<Capturing argument>);
Wanted 1 time:
-> at foo.TestClass.testName(TestClass.java:64)
But was 2 times. Undesired invocation:
-> at agh.TestClass.testName(TestClass.java:61)

    at foo.TestClass.test(TestClass.java:64)
    [..]
```

The test fails because the ArgumentCaptor stores every type, because the type information is erased a runtime. How can we capture the type that is specified in the captor, in this case `ArrayList`?  It is possible to implement an `Answer `that stores the argument, and use
`Matchers.isA(ArrayList.class) `but thats ugly->

` doAnswer(captureArg1).when(consumer).accept(isA(ArrayList.class));`

Maybe it is a good idea to create a pull req and extend the ArgumentCaptor API by adding a method like `<T> T captureIf(ArgumentMatcher<? extends T>) `?

Then we could write:
`verify(consumer).accept(captor.captureIf(isA(ArrayList.class)));`

### PR DESCRIPTION
**Pull request by terebesirobert**
This fixes #358

I added a CustomCapturingMatcher to ArgumentCaptor. This will store the data based on a ArgumentMatcher.
For example:
```java
Processor mock = ...

mock.process(new ArrayList<>);
mock.process(new HashSet<>);

ArgumentCaptor captor = ...

verify(mock).process(captor.capture());
```
the CapturingMatcher inside the captor will capture the list and set too (the implementation does not perform any type check on the arguments).

I added a new conditional capture method mock.captureIf(ArgumentMatcher) that will store data based on the matcher received as argument.

This will save a lot of time when writing unit tests.

check list

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/2.x/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by terebesirobert** [comment]
@TimvdLippe created a new pull request.. Thanks for the help

**Comment by TimvdLippe** [comment]
@terebesirobert Many thanks, I will review this PR tomorrow :smile:

**Comment by terebesirobert** [comment]
@TimvdLippe I had to add some weird casts to make it compile. I will try to fix them next week, I'm off this weekend. Thanks

**Comment by terebesirobert** [comment]
@TimvdLippe Do you have any ideas how can I fix this?

**Comment by TimvdLippe** [comment]
Hm it seems like it does not like the list. The PR is quite big right now and sadly I won't have a lot of time the coming weeks. Maybe you can incrementally make the changes and ensure that it compiles on every step without casts? If you do it per commit, you might have an easier time fixing it.

**Comment by TimvdLippe** [comment]
Closing this PR as stale. Feel free to open a new PR if you are still interested in landing these changes. (But please reduce the size of the PR to make it more easily reviewable)

**Pull request closed without merging**
