### PR TITLE
Migrate to JaCoCo `0.8.11`

### PR DESCRIPTION
**Pull request by valfirst**
Bump JaCoCo to fix compatibility with the latest Java versions: https://github.com/jacoco/jacoco/releases

## Checklist

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [ ] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [ ] The pull request follows coding style
 - [ ] Mention `Fixes #<issue number>` in the description _if relevant_
 - [ ] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Not sure why a bump of Jacoco would start failing these tests. It might be that they have always been flaky and that they rely on ordering. Do you mind debugging locally what is going on here and if you can reproduce the same issues with the same Jacoco version, but with different ordering?

**Comment by TimvdLippe** [comment]
@raphw I think adding these flags for our tests is okay, but what do you think?

**Comment by raphw** [comment]
I think so, yes. I'd go for it.

**Comment by valfirst** [comment]
CI is green, one job fails at Codecov upload:

> Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v3/dist/codecov' failed with exit code 255

**Pull request merged**
