### PR TITLE
Remove JDK env, not corresponding with jdk used

### PR DESCRIPTION
**Pull request by pzygielo**
- [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each  commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [ ] Mention `Fixes #<issue number>` in the description _if relevant_
 - [ ] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Superseded by #1750

**Comment by pzygielo** [comment]
> Superseded by #1750

Nope.

It was still draft based on #1745. I was waiting for that base to be merged first, to have only https://github.com/mockito/mockito/pull/1752/commits/3aea73bd35a47cb151f419664377c00a480d8107 in that PR.

**Comment by pzygielo** [comment]
Could you please re-open? I'll force-push that rebased single commit I meant for this PR.

**Comment by TimvdLippe** [comment]
Next time, please combine them in 1 PR. That makes maintenance a lot easier.

**Comment by pzygielo** [comment]
> Next time, please combine them in 1 PR. That makes maintenance a lot easier.

For my excuse: This change seemed cosmetic only. It was not in jobs I changed in earlier PR. I wasn't 100% sure that this env variable had no control over some test execution. That's why I chose to raise it as separate PR, and as draft - mainly to go through Travis.

But perhaps I could base it on main branch, not on those two unaccepted commits.

**Pull request merged**
