### PR TITLE
Verifies #688: Acceptance test to prevent future regression

### PR DESCRIPTION
**Pull request by jpenglert**
Added an acceptance test to verify #688

### CODE REVIEW

**Comment by jpenglert** [comment]
This is going to fail until Mockito updates to the next version of byte buddy (that re-fixes #688) that contains the following commit: 

https://github.com/raphw/byte-buddy/commit/98eaf113681b97053419b292ff342f4ea3321879

**Comment by TimvdLippe** [comment]
Could you rebase on `release/2.x`? This test should pass now :smile:

**Comment by jpenglert** [comment]
@TimvdLippe Rebased on `release/2.x` and tests are passing now

**Comment by szczepiq** [comment]
Thank you guys! Nice and clean change, and makes Mockito safer for our users!!!

**Pull request merged**
