### PR TITLE
Add Java 21 to CI build matrix

### PR DESCRIPTION
**Pull request by valfirst**
Add Java 21 (LTS) to CI build matrix

## Checklist

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [ ] The pull request follows coding style
 - [ ] Mention `Fixes #<issue number>` in the description _if relevant_
 - [ ] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by valfirst** [comment]
Blocked by #3146

**Comment by TimvdLippe** [comment]
Seems like CodeCov is having some issues 😢

**Comment by TimvdLippe** [comment]
Seems like the upload token doesn't work on PRs: https://github.com/codecov/codecov-action/issues/837#issuecomment-1530053511

**Comment by TimvdLippe** [comment]
Yeah unfortunately it is 😢 But the rest works, so let's merge this. Thanks for the work!

**Pull request merged**
