### PR TITLE
Fix whitespace issues throughout the code

### PR DESCRIPTION
**Pull request by mureinik**
This patch applies de-facto standards the codebsae currently has regarding whitespaces on all the java files in the project:

- Newlines were added at the end of files that didn't have them.
- Whitespaces at the end of source lines were removed.

All these changes were done by running `sed` on the codebase. The exact details can be found in the individual commit messages.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Cool that was easier tp fix than I thought. I think we should enforce this with a simple Checkstyle rule. @mockito/developers WDYT about adding checkstyle to only enforce these two rules?

**Comment by mureinik** [comment]
@TimvdLippe Adding such a checkstyle is pretty easy to do. If @mockito/developers agree this is the right way to go, I'd happily contribute such a patch, either on this PR or on a separate one, whatever makes more sense to you.

**Comment by mureinik** [comment]
For the reference, here's an example of a path adding these checkstyle rules (didn't want to post a patch and clatter up this PR before there's an agreement on the subject)

[0001-Checkstyle-conf.-to-enforce-whitespace-rules.patch.gz](https://github.com/mockito/mockito/files/752243/0001-Checkstyle-conf.-to-enforce-whitespace-rules.patch.gz)

**Comment by szczepiq** [comment]
@mureinik, thank you for contribution and dedicating time to Mockito!

@TimvdLippe, @mureinik, it is a great idea to enforce checkstyle! Consistent code style makes codebase easier to work with.

What is the practical benefit of enforcing whitespace at the end of line / file? I vote for enforcing practical rules that help maintaining the project VS rules that fail the build occasionally, triggering extra effort from developers, without adding much value.

If you want to fix whitespace in the project or set a checkstyle rule for it, then go for it. If checkstyle rule becomes a hindrance we can always tweak it.

@mureinik, do you want to contribute an enhancement to Mockito? How about #685?

**Comment by TimvdLippe** [comment]
Discussion regarding usefulness was resolved in Slack. Will have to quickly check if there were no unintended changes. Other than that this is ready for merging!

Could you open a new PR after this one with the checkstyle config? We can continue the discussion there regarding the rules we want to enforce and how. Thanks for your time and effort!

**Comment by mureinik** [comment]
@TimvdLippe Agreed. I'll open a new PR for the checkstyle stuff after this one is merged, so I can easily rebase on top of it.

@szczepiq Sure, I'll take a look at #685 - looks interesting.

**Comment by szczepiq** [comment]
Great work! We discussed it on slack. Clean whitespace / checkstyle will help with git workflows for cleaner history.

@TimvdLippe, do we want this also in release/2.x for easier merges?

**Comment by TimvdLippe** [comment]
@szczepiq I am cherry-picking it into release/2.x atm

**Pull request merged**
