### PR TITLE
Fixes #1516 and #1631 : Allows @Spy with @InjectMocks to be injected into other @InjectMocks

### LINKED ISSUE #1516: @Spy @InjectMocks dependency A->spy(B)->C not injected correctly when using constructor dependency injection
I am trying to do a test on class A, with a dependency A->B to be spied, and a transitive dependency B->C

This code is typical in a spring application, when A is a high-level service, C is a low-level one (like a Repository), and B is simply a helper service class that delegate most calls to C

To use @Spy on instance of B, requires to mock C, and inject C into B... 
a typical test code should be 
`
   @RunWith(MockitoJUnitRunner.class)
   class Test {
        @InjectMocks A a;
	@Spy @InjectMocks  B b; 
        @Spy C c;

       @Test  public void testA() { .. }
}
`

This generally works fine with standard spring injections for code like 
`
   @Component // or @Service, @Controller, ..
   public class B {
      @Autowired // or @Inject
      private C c;
   }
`

... BUT fails  when using Constructor dependency injection for fields !!!
This is absurd since constructor injection is precisely a best practice for enforcing code stability regarding  test

`
   @Component
   public class B {
      private final C c;
      public B(C c) { this.c = c;  }
   }
`

There are many strange situations, while testing different combinations of annotations on real class (@Inject, @Autowired..), and @Spy @InjectMocks in test class

Either 
case 1/ spy NOT injected in  a.b   ... so causing NPE in spy execution
case 2/ spy NOT injected in b.c ... but injected in a.b  ... so causing NPE in spy execution
case 3/ MockitoException Unable to initialize @Spy annotated field 'b', Please ensure that the type 'CtorB' has a no-arg constructor

Notice also that the final desired scenario would be to use lombok generated full constructor.. but it also fails !!
`
	@InjectMocks 
	A a; // ERROR.. a.b == null
	
	@Spy @InjectMocks
	B b; // b instanciated, but not injected into a !!!

	@Spy
	C c;

    // with..
    @AllArgsConstructor(onConstructor_={@Inject}) // equivalent of :  @Inject public A(B b) { this.b = b; }
    public class A {
	private final B b;
    }
   // or also 
   @AllArgsConstructor
   public class A {
	private final B b;
   }
`

I have joined a full maven test project that reproduce many of these scenarios
[test-mockito.zip](https://github.com/mockito/mockito/files/2466624/test-mockito.zip)

You can also browse it (up-to-date) here : 
[https://github.com/Arnaud-Nauwynck/test-snippets/tree/master/test-mockito]

### PR DESCRIPTION
**Pull request by arnor2000**
check list

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/2.x/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [x] At least one commit should mention `Fixes #<issue number>` _if relevant_

This PR aims to fix #1516 and #1631. I know and understand dependency injection is not priority of Mockito team but discussion on #1518 convinces me to propose a fix. Like @mockitoguy I think DI in Mockito is useful and most of reported issues denote users high expectations for a helpful feature rather than the fact it's broken.

Basically this PR allows fields annotated with @Spy and @InjectMocks to be injected into other fields annotated with @InjectMocks and so on.
It may also be a response to #174, the need to a @Real annotation, actually I think most usage of @Spy and @InjectMocks combination is a workaround to such annotation.

Because PR ended to change a bunch of classes, I will highlight main changes.

"Entry point" of changes is InjectingAnnotationEngine, I add a loop of mock injection. The loop uses variants of existing field injection strategies documented in DefaultInjectionEngine.

To facilitate field injection strategies variants (StrictConstructorInjection and LenientPropertyAndSetterInjection), I merge ConstructorArgumentResolver (contract to find constructor arguments) and ConstructorInstantiator (contract to find and instantiate constructor) interfaces into an unique ConstructorResolver interface representing a strategy to find a constructor and its arguments. Constructor instantiation part comes back into FieldInitializer.

The fact to merge these two interfaces into ConstructorResolver leads to a better separation of concerns between finding constructor and its arguments in one side and instantiation, initialization and field injection on the other side. isResolvable() allows some tuning between the inclination of strategy implementations to fail with exception or handle failure softly. Moreover it's opening future smarter behaviors, for example BiggestConstructorResolver could try to resolve biggest constructor matching actual available mocks.

I hope you will appreciate this work.

### CODE REVIEW

**Comment by TimvdLippe** [comment]
It's awesome that you worked on this issue, but this PR is quite large. It will take us quite some time to review and we are busy with some other things as well. Hopefully we can give your a proper code review soon. (I had a quick glance and the code seems good, so that's a good sign 😄 )

**Comment by bric3** [comment]
Hi @arnor2000 thanks for contributing on this, I will take a look as soon as I have some free time.

**Comment by arnor2000** [comment]
@bric3, OK I cherry picked changes to release/3.x into PR #1711 without any conflict. I let you decide to close one or other PR at your convenience.

**Comment by TimvdLippe** [comment]
Superseded by #1711

**Pull request closed without merging**
