### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by davidkarlsen**
Fixes for #374 - more left though.

### CODE REVIEW

**Comment by ChristianSchwarz** [comment]
@davidkarlsen 

 * [ ] The method [Mockito.stubVoid(..)](https://github.com/mockito/mockito/blob/master/src/main/java/org/mockito/Mockito.java#L1889) is deprecated but not annotated with `@Deprecated`, can you remove too?

**Comment by davidkarlsen** [comment]
On it - I'll be back! (the terminator) :)

**Comment by davidkarlsen** [comment]
OK, added removal of stubVoid in https://github.com/davidkarlsen/mockito/tree/removeStubVoid (which is a fork of this PR).

**Comment by davidkarlsen** [comment]
WDYT?

**Comment by ChristianSchwarz** [comment]
@davidkarlsen Looks good! There is only one reference in the JavaDocs that should be removed, I added a note in your commit.

**Comment by davidkarlsen** [comment]
@ChristianSchwarz fixed - ping

**Comment by davidkarlsen** [comment]
@szczepiq Intersted in this?

**Comment by szczepiq** [comment]
Love it. Thanks!

**Comment by davidkarlsen** [comment]
@szczepiq What about https://github.com/mockito/mockito/pull/394 (which is https://github.com/davidkarlsen/mockito/tree/removeStubVoid) - if you read the thread above?

**Pull request merged**
