### PR TITLE
Removes deprecated way of documenting package by package-info.java

### LINKED ISSUE #665: Use package-info.java instead of the old html file
`package-info.java` can be annotated, and reflection can be used, this may be useful at some point, or not.

### PR DESCRIPTION
**Pull request by bric3**
Should fix #665 

Nothing to say really, but it has to be done at some point. The most important selling point is that it may allow to annotate a package.

### CODE REVIEW

**Comment by bric3** [comment]
Thanks @TimvdLippe I believe this is OK javadoc wise

**Comment by TimvdLippe** [comment]
I trust you then 😄

**Comment by bric3** [comment]
Around midnight? 😛

**Comment by szczepiq** [comment]
Nice change, thanks for keeping the codebase clean!!!

**Pull request merged**
