### PR TITLE
Migrate settings.gradle to settings.gradle.kts

### PR DESCRIPTION
**Pull request by epeee**
a very first step towards  #1359

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Awesome, thanks for taking a stab at this. I will need to see this in the editor and how it all works. Will hopefully have some time next weekend to do so!

**Comment by epeee** [comment]
It looks like we have to wait for Gradle 4.7 due to failing builds while using Java 10.
This problem should be fixed in https://github.com/gradle/kotlin-dsl/releases/tag/v0.16.3 (will be part of Gradle 4.7).

**Comment by TimvdLippe** [comment]
I am still interested in using Kotlin rather than Groovy for our build files. However, the files changed a bit. Do you want to open a new PR for that?

**Comment by epeee** [comment]
@TimvdLippe a new PR is ready for review.

**Pull request closed without merging**
