### PR TITLE
Fixes #2510: Remove ExpectedException from internal test suite

### LINKED ISSUE #2510: Remove `ExpectedException` from internal test suite
The rule is not ideal, as it will trigger even if the test fails for a completely different reason. Instead, we should use `assertj` with `assertThatThrownBy` to denote which specific line should trigger the exception.

### PR DESCRIPTION
**Pull request by temp-droid**
## Checklist

 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)
 - [x] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [x] If possible / relevant include an example in the description, that could help all readers
       including project members to get a better picture of the change
 - [x] Avoid other runtime dependencies
 - [x] Meaningful commit history ; intention is important please rebase your commit history so that each
       commit is meaningful and help the people that will explore a change in 2 years
 - [x] The pull request follows coding style
 - [x] Mention `Fixes #<issue number>` in the description _if relevant_
 - [ ] At least one commit should mention `Fixes #<issue number>` _if relevant_

### CODE REVIEW

**Comment by temp-droid** [comment]
Hey @TimvdLippe!

Outside one `ExpectedException` case in `SpyAnnotationTest` that I'm unsure of (not used in the past?) and one `@Test(expected…` in the `osgi-test` I'm not confortable touching, the rest should be replaced.

Before continuing replacing the `try fail finally` cases, I wanted to check with you if it wouldn't be best to create another PR for those. We are already at 72 commits for this one and I counted more than 380 occurrences in ~120 files for `fail()`.

I feel like this would be too much to review in a single PR, but you tell me.

**Comment by TimvdLippe** [comment]
Yes. This PR is already massive, so let's cut it here. I hope to have time on Friday to review. Thanks for your effort!

Note that in this case I am okay with so many commits, since it is mechanical. However, for other PRs let's try to keep them small 😄

**Comment by temp-droid** [comment]
Do you have suggestions how to approach the new PR? First creating an issue to link it to? Or referencing the same one?

I'm afraid it might create confusion to have 2 PRs for the same issue qua closing.

**Comment by TimvdLippe** [comment]
Let's file a new issue for that. Thanks!

**Review by TimvdLippe — APPROVED** [review]
Thanks for the cleanup!

**Pull request merged**
