### PR TITLE
Unified logic of argument matching and capturing

### LINKED ISSUE #439: ArgumentCaptor and ArgumentMatcher can't be mixed in varargs
In the given test below the ArgumentCaptor should captor only the char 'c':

```
    @Captor
    private ArgumentCaptor<Character> argumentCaptor;
    
    @Test
    public void capturesVararg() throws Exception {
        mock.varargs(42, 'c');

        verify(mock).varargs(eq(42), argumentCaptor.capture());
       
       assertThat(argumentCaptor.getAllValues()).containsExactly('c');
    }
```

The test fails with this message:

```
Actual and expected should have same size but actual size was:
  <2>
while expected size was:
  <1>
Actual was:
  <[42, 'c']>
Expected was:
  <['c']>
```

Note that we see here 2 bugs:
 - a wrong argument index was captored
 - an `int `was captored by an  `ArgumentCaptor<Character> ` -> #565

### LINKED ISSUE #583: ArgumentCaptor: NPE when an null array is passed to a varargs method
A NullPointerException is thrown if an null array is passed to a varargs method.

```
@Test
public void shouldCaptureVarArgs_nullArrayArg() {
        String[] argArray = null;
        mock.varargs(argArray);

        verify(mock).varargs(captor.capture()); //<- Kaboom NPE
}
```

Since an vararg is simply an array the ArgumentCaptor should reject it silently. This relates to #565.

```
java.lang.NullPointerException
	at java.lang.reflect.Array.getLength(Native Method)
	at org.mockito.internal.invocation.InvocationMatcher.captureVarargsPart(InvocationMatcher.java:142)
	at org.mockito.internal.invocation.InvocationMatcher.captureArgumentsFrom(InvocationMatcher.java:122)
	at org.mockito.internal.invocation.InvocationMarker.markVerified(InvocationMarker.java:24)
	at org.mockito.internal.invocation.InvocationMarker.markVerified(InvocationMarker.java:18)
	at org.mockito.internal.verification.checkers.NumberOfInvocationsChecker.check(NumberOfInvocationsChecker.java:43)
	at org.mockito.internal.verification.Times.verify(Times.java:40)
	at org.mockito.internal.verification.MockAwareVerificationMode.verify(MockAwareVerificationMode.java:21)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:73)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:32)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:37)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:36)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.access$0(MockMethodInterceptor.java:32)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:113)
	at org.mockitousage.IMethods$MockitoMock$81506210.varargs(Unknown Source)
	at org.mockitousage.matchers.VarargsTest.shouldCaptureVarArgs_nullArrayArg(VarargsTest.java:182)
```

### PR DESCRIPTION
**Pull request by ChristianSchwarz**
The logic of argument matching and capturing is the same but can be found in ArgumentsComparator and InvocationMatcher. This PR unifies the decision logic how matchers are applied to argument+varargs by introducing a `MatcherApplicationStrategy`. This strategy can apply an action to an pair of ArgumentMatcher and Argument. One action is used to perform the ArgumentMatcher.matches(arg) call and an other is used to perfrom the capturing.

 * fixes #439 ArgumentCaptor and ArgumentMatcher's can now be mixed in varargs
 * fixes #583 No more NPE when null is passed to an varargs 
 * added 25 regression tests in VarargsTest (5 are ignored cause they belong to other issues and fail currently) 
 * reduced logic duplication

### CODE REVIEW

**Comment by bric3** [comment]
on hold as we need to address the beta release thing

**Comment by ChristianSchwarz** [comment]
Since these 2 bugfixes will not be included in the 2.1.0 RC phase, should I send a new PR against release/2.x ?

**Comment by szczepiq** [comment]
@ChristianSchwarz, yes, but let's wait until 2.1.0 is out. This way, nobody gets confused :)

**Comment by bric3** [comment]
@ChristianSchwarz I've changed the base branch to `release/2.x`

**Comment by ChristianSchwarz** [comment]
> [..] let's wait until 2.1.0 is out. This way, nobody gets confused :)

**@mockito-team**
Now I am confused! Who can mockito users be confused by bugfixes? 

In the meantime on the `master` branch...
 * refactorings were merged like #656 and #654
 * new features are going to be merged too #648 
 * but bugfixed won't be merged ?

**Comment by TimvdLippe** [comment]
We wanted to freeze the release branch while waiting for the RC. #648 is a special case which originates from JavaOne, a major selling point for Mockito. We dont plan to add other changes in the RC.

**Comment by bric3** [comment]
@ChristianSchwarz this thing will go in 2.2, I mean it ;)
I think Capturing matcher deserves an overfaul, and I like the enhancement you've made, but feature freeze is essential, sorry for the longer RC phase, but I think it's for the better ;)

**Comment by bric3** [comment]
@ChristianSchwarz By the way could you rebase your commits on top of `release/2x`, because git seems to see unrelated commits form @TimvdLippe

**Comment by ChristianSchwarz** [comment]
@bric3 This PR is now rebased on `release/2x`. It the `master` now used for mockito 3.x ?
@all If you have some time besided the numerous CI-tasks, please review this PR.

**Comment by bric3** [comment]
Great thanks. It may be delayed again due to some disagreement on the CI-CD...

Otherwise yes the master is for mockito 3.x. I should probably update the contributing guide and the template as well

**Comment by bric3** [comment]
Some adjustments can be made e.g. `getArgumentType` can be simplified to read the type arg on the class rather than looking at the method. But it's a nice code improvement.

**Comment by szczepiq** [comment]
@ChristianSchwarz, this is an impressive code change, improving not only the behavior but also code and test coverage!!! THANKS!

Thanks @bric3 for reviewing and merging the PR!

**Comment by ChristianSchwarz** [comment]
@bric3 
>Some adjustments can be made e.g. getArgumentType can be simplified to read the type arg on the class rather than looking at the method. 

The mechanic remained unchanged in this RP, I introduced it with #463. At first I tried to retrieve the Type-Argument from the class but this turned out to be more complex. E.g. when the type-argument is bound in an upper class or interface or additional type-arguments were introduced on a matcher class.
Anyway if you have an idea how to improve or simplify it let me now!

>Other improvements can be made later. 
Sounds good, can you open a new ticket, so I can take look.

**Comment by ChristianSchwarz** [comment]
@mockito-core
#606 can be closed now

**Comment by bric3** [comment]
>> Other improvements can be made later.

> Sounds good, can you open a new ticket, so I can take look.

At the moment this works quite well! So no hurry, especially given your above remark. On mockito 3 (on master atm) we could change the interface to allow reporting the type handled by the matcher and maybe use default method for that.

**Comment by bric3** [comment]
@ChristianSchwarz I have seen an interesting problem with `VarargsTest` fail on master, which is JDK 8 only, while the same test passes on release/2.x which is compiled and run against 3 JDK 6/7/8. I'm not sure why at the moment this behavior is different . Plus my dev laptop is being fixed for a few days, so I'm limited in my debug right now.

This happened after a merge of release/2.x to master (52df10af105b7e9cd45bf214141c5096db3ecafe).

I noticed that `verify(mock).varargs(isNull());` is compiled to invoke `IMethods.varargs(String ... string)`. I'm not sure other JDKs behave/compile differently though. 

One of the failing test can be fixed by adding the cast statement

```
    @Test
    public void shouldMatchVarArgs_nullArrayArg() {
        Object[] argArray = null;
        mock.varargs(argArray);

        verify(mock).varargs((Object[]) isNull()); // otherwise it is linked against String[]
    }
```

Could it be that something went wrong with the merge regarding this PR ?

**Comment by bric3** [comment]
@ChristianSchwarz Actually the investigation continue, see https://github.com/mockito/mockito/issues/717#issuecomment-256632518

**Pull request merged**
