### PR TITLE
Feature/list collection matchers

### PR DESCRIPTION
**Pull request by JeroenMols**
This pull requests adds basic support for Mockito collection  matchers to simplify doing verifications on standard Java collections. At this stage only the most prominent list collection matchers have been built.

I've added the following matchers:
```
verify(mock).someMethod(listContains(expectedObject));
verify(mock).someMethod(listContains(expectedObject, index));
verify(mock).someMethod(listContainsNull());
verify(mock).someMethod(listDoesNotContain(wrongObject));
verify(mock).someMethod(listDoesNotContain(wrongObject, index));
verify(mock).someMethod(listDoesNotContainNull());
verify(mock).someMethod(listOfSize(3));
```
Thereby basically moving my personal project into Mockito: https://github.com/JeroenMols/MockitoCollectionMatchers

I did my best to adhere to the coding standards and guidelines. Please let me know if you have any questions.

### CODE REVIEW

**Comment by ChristianSchwarz** [comment]
I think it is already possible with Hamcrest. The proposed API could be more generic e.g iterableOfSize() instead listOfSize(), the same goes for the other proposals.

**Comment by JeroenMols** [comment]
Maintenance is indeed a valid concern, but you'll always have to balance that vs easy of use. E.g. iterableOfSize() isn't exactly what a user may expect, but we could also redirect a listOfSize() and setOfSize() both to a iterableOfSize(). That would tradeoff the maintenance burden vs easy of use.

Please advice how you want to proceed.

**Comment by JeroenMols** [comment]
Any update on this pull request? I'm very eager to help out getting this integrated (or make changes to make this PR fit)

**Comment by TimvdLippe** [comment]
I still have an extensive Mockito API investigation planned to see what our current API surface is. Based on that outcome, we have to decide whether we want to expand our public API in this direction. Therefore this PR is blocked on that process, sorry :cry:

**Comment by TimvdLippe** [comment]
I don't think we want to increase our API surface with these kind of matchers, so therefore I am closing this PR. Feel free to publish them in a separate utility project though!

**Pull request closed without merging**
